### ISSUE TITLE
Run golangici-lint during CI

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#1109]
Linter (golangci-lint) should be enabled and configured so that new builds don't fail on current lint errors.

**Comment by charith-elastic** [comment]
Ideally we want to run all the linters bundled with golangci-lint and exclude only those that produce too many false positives.

On the current master (HEAD = 11b861487a7748f23a8d7ba6a82a77a81870672e) running the following command in the `operators` directory produces [~1438 warnings](https://github.com/elastic/cloud-on-k8s/files/3373187/lint_warnings.txt).
```
 golangci-lint run --enable-all --max-issues-per-linter 0 --max-same-issues 0 --out-format tab --deadline 90s 
```

There are some obviously noisy linters we can exclude from the outset
- `lll`: Warning on lines longer than 120 characters. Generated code and some complex log lines are difficult to keep under the character limit. 
- `dupl`: Duplicate code detection. Mostly identifies testing code as duplicates. Some are false positives and some are difficult to eliminate without major refactoring.
- `gochecknoglobals` and `gochecknoinits`: Warns on global variable declarations and `init` functions which are extremely difficult to avoid in a Kubernetes code base.

Some linters can be selectively disabled on certain paths (eg. tests)
- `unparam`: Detect parameters that are unused or only ever gets passed a single value.
- `scopelint`: Detect the reuse of variables within a range loop. This linter produces many false positives.

Current plan is to go through each of the warnings and fix the code where possible. For complicated problems and/or false positives, appropriate exclusion rules will be added to the default configuration file `.golangci.yml`.

**Comment by charith-elastic** [comment]
Fairly trivial linter warnings have been fixed and can be seen in #1222 . However, there are still a few more issues remaining that require input from the whole team because fixing those issues would result in non-trivial changes to the code base. Please consider the following list and comment on any items that you think should be left as is without fixes.


Logic Bugs
----------
- pkg/controller/elasticsearch/version/supported_versions.go:32:3: SA4004: the surrounding loop is unconditionally terminated (staticcheck)
- pkg/utils/k8s/client.go:151:18: SA4009: argument cfg is overwritten before first use (staticcheck)

Dead Code
---------
- pkg/controller/elasticsearch/keystore/keystore.go:89:19: U1000: func `keystore.readSettingFileContent` is unused (unused)
- pkg/controller/license/validation/validations.go:42:18: U1000: func `Context.isCreate` is unused (unused)

Stuttering
-----------
- pkg/controller/common/license/labels.go:23:6: type name will be used as license.LicenseType by other packages, and that stutters; consider calling this Type (golint)
- pkg/controller/common/license/model.go:30:6: type name will be used as license.LicenseSpec by other packages, and that stutters; consider calling this Spec (golint)
- pkg/controller/common/license/model.go:95:6: type name will be used as license.LicenseStatus by other packages, and that stutters; consider calling this Status (golint)
- pkg/controller/common/user/finalizer.go:17:6: func name will be used as user.UserFinalizer by other packages, and that stutters; consider calling this Finalizer (golint)
- pkg/controller/common/volume/volume.go:13:6: type name will be used as volume.VolumeLike by other packages, and that stutters; consider calling this Like (golint)
- pkg/controller/elasticsearch/mutation/comparison/comparison.go:26:6: func name will be used as comparison.ComparisonMismatch by other packages, and that stutters; consider calling this Mismatch (golint)
- pkg/controller/elasticsearch/restart/restart.go:25:6: type name will be used as restart.RestartContext by other packages, and that stutters; consider calling this Context (golint)
- pkg/controller/elasticsearch/user/credentials.go:48:6: type name will be used as user.UserCredentials by other packages, and that stutters; consider calling this Credentials (golint)

... and a lot more

Return Type Order
-----------------
- pkg/controller/elasticsearch/keystore/config.go:90:1: error should be the last type when returning multiple items (golint)
  func NewConfigFromFlags() (Config, error, string) {
- pkg/controller/elasticsearch/keystore/updater.go:147:1: error should be the last type when returning multiple items (golint)
  func (u *Updater) updateKeystore() (error, string) {

Mixed access levels
-------------------
- pkg/dev/portforward/forwarder_store.go:23:26: exported func NewForwarderStore returns unexported type *portforward.forwarderStore, which can be annoying to use (golint)
- pkg/controller/common/license/verifier.go:124:41: exported func NewSigner returns unexported type *license.signer, which can be annoying to use (golint)
- pkg/dev/portforward/forwarder_store.go:23:26: exported func NewForwarderStore returns unexported type *portforward.forwarderStore, which can be annoying to use (golint)
- pkg/dev/portforward/pod_forwarder.go:70:78: exported func NewPodForwarder returns unexported type *portforward.podForwarder, which can be annoying to use (golint)
- pkg/dev/portforward/pod_forwarder_test.go:36:66: exported func NewPodForwarderWithTest returns unexported type *portforward.podForwarder, which can be annoying to use (golint)
- pkg/dev/portforward/service_forwarder.go:48:71: exported func NewServiceForwarder returns unexported type *portforward.serviceForwarder, which can be annoying to use

Identifier Case
---------------
- pkg/controller/common/license/verifier.go:193:2: struct field `Uid` should be `UID` (golint)
- pkg/controller/common/user/external.go:61:23: method Id should be ID (golint)
- pkg/controller/elasticsearch/settings/fields.go:24:2: const `XPackSecurityHttpSslCertificate` should be `XPackSecurityHTTPSslCertificate` (golint)
- pkg/controller/elasticsearch/settings/fields.go:25:2: const `XPackSecurityHttpSslCertificateAuthorities` should be `XPackSecurityHTTPSslCertificateAuthorities` (golint)
- pkg/controller/elasticsearch/settings/fields.go:26:2: const `XPackSecurityHttpSslEnabled` should be `XPackSecurityHTTPSslEnabled` (golint)
- pkg/controller/elasticsearch/settings/fields.go:27:2: const `XPackSecurityHttpSslKey` should be `XPackSecurityHTTPSslKey` (golint)
- pkg/controller/elasticsearch/user/user.go:50:15: method Id should be ID (golint)
- pkg/controller/kibana/config/fields.go:12:2: const `XpackMonitoringUiContainerElasticsearchEnabled` should be `XpackMonitoringUIContainerElasticsearchEnabled` (golint)

**Comment by thbkrkr** [comment]
I am in favor of fixing everything, without hesitation for Logic Bugs, Dead Code and Return Type Order but without strong opinion for Stuttering, Mixed access levels and Identifier Case.

**Comment by sebgl** [comment]
Thanks for categorising all those!
+1 with what @thbkrkr: let's fix logic bugs, dead core and return type order first.

* Stuttering: I would be in favour of leaving them aside, to the responsibility of each developer (sometimes I feel like it *does* make sense for a function name to stutter a little bit).
* Mixed access level: let's fix those, probably by making the function return an interface, or keeping it private.
* Identifier Case: I would also be in favour of fixing them, for code consistency.

**Comment by jonsabo** [comment]
Agreed with the others. This made me smile though
>pkg/controller/elasticsearch/settings/fields.go:26:2: const XPackSecurityHttpSslEnabled should be XPackSecurityHTTPSslEnabled (golint)
