### ISSUE TITLE
Remove PVCs when removing StatefulSets nodes

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1288]
When we scale down or remove a StatefulSet, we don't remove associated PVCs of nodes that have been removed.
The StatefulSet controller itself does not remove PVCs either.

This can lead to confusing scenarios:

- scale down a cluster, then scale it up 3 months later: it will reuse 3-months old volumes
- remove a cluster, create it again with the same name: it will reuse the old cluster data

I think we should remove PVCs (I don't see why not), but not necessarily remove the associated PVs: leave that up to the storageClass reclaim policy.

**Comment by sebgl** [comment]
Related Kubernetes issue to have it part of the StatefulSet spec: https://github.com/kubernetes/kubernetes/issues/55045

**Comment by sebgl** [comment]
We discussed making this an option of the Elasticsearch CRD:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.2.0
  nodes:
  - name: hot
    nodeCount: 3
  - name: warm
    nodeCount: 2
    deletePVC: false
```

We could distinguish downscales (eg. 3 -> 1 nodes) from StatefulSet removal (eg. 3 -> 0 nodes).
I think this setting would apply in both cases?

I also think this should be opt-out (default to removing PVCs).

**Comment by thbkrkr** [comment]
The current behavior of removing PVC when removing the pods/sset seems to me completely logical and conveninent so I am completely to keep it. Be able to opt-out would also be very nice.

**Comment by anyasabo** [comment]
I'm also for removing PVCs when we remove a pod, and perhaps working with upstream to integrate that as part of sset functionality.

Going by the linked issue, ssets do not delete the PVCs to make scaling up quicker. That's not very persuasive to me, but I don't have any data to support either. I doubt people will be scaling up and down often enough for that to be a significant benefit, especially when compared to the "surprise" of scaling down an ES cluster but still paying for the data.

My understanding is that we already have this behavior without stateful sets (when we delete a pod, we delete a PVC no questions asked), so there's also at least some precedent for this in our product.

I don't really feel strongly either way about being able to toggle this behavior in the ES spec. My inclination is to only delete the PVCs for now. If we end up wanting to be able to opt in or out in the future we can add a switch then.

If someone can clarify the current use case for leaving the data around but removing the nodes in SaaS (I think it was described as "pausing"?) I would appreciate it.



>When we scale down or remove a StatefulSet, we don't remove associated PVCs of nodes that have been removed.
>...
>remove a cluster, create it again with the same name: it will reuse the old cluster data

For this point, we can and should set an owner ref on the PVC to the ES instance IMO. So that if the ES instance is deleted, the PVCs are as well. This does not help with scaling down pods on an existing instance though.

**Comment by pebrc** [comment]
I wonder though if our feeling that keeping the PVCs is annoying and hard to debug is due to the fact that we are in dev mode where we constantly spin up clusters with the same name and that this behaviour could turn out to be a feature in 'production' mode where you would want to err on the side of keeping data around? It can be useful if a user accidentally deletes a cluster and improves recovery over a restore from snapshot (if the user have snapshots)

I don't feel super strongly for keeping the PVCs though. 

If we decide to go with deleting the PVCs by default despite this concern I think finding the right flag name/toggle is important. 
`deletePVC` on the node level leaves me wondering what this actually does, should it be on the cluster level and affect all nodes to same extent. Why would you only want to delete parts of your data and keep other nodes around. Is that not what retention in ILM is for, why are we trying to recreate that here? So maybe a top-level `retainPVConDelete` or something like that?

**Comment by anyasabo** [comment]
> I wonder though if our feeling that keeping the PVCs is annoying and hard to debug is due to the fact that we are in dev mode where we constantly spin up clusters with the same name and that this behaviour could turn out to be a feature in 'production' mode where you would want to err on the side of keeping data around? It can be useful if a user accidentally deletes a cluster and improves recovery over a restore from snapshot (if the user have snapshots)

I think if that's a concern, it can be controlled by the storage class and shouldn't be something that we need to worry about.

**Comment by pebrc** [comment]
Let's delete the PVC for now without any config option to control the behaviour.

**Comment by sarjeet2013** [comment]
Hi, Is there any update or fix planned for this?

If not, I am trying to locally test a fix where the ownerReference can be applied on pvc and it will be taken care on pod/statefulset delete. I think, exposing a configuration on CRD can help in adding ownerReference from Pod/Statefulset, so the PVC deletion can happen for either pod/Statefulset delete resp. Any feedback or suggestion on this approach?

**Comment by sebgl** [comment]
> the ownerReference could be for pod instead of statefulsets, and that would take care of deleting pvc on pod deletion

The problem with that is we do delete pods when a rolling upgrade is required. Eg. if you change something on the ES node configuration, or set a higher memory limit on the pod. We delete the pod ourselves (when the cluster is ready for it), then we let the StatefulSet controller recreate it, and reuse the same PVC automatically. We want to keep that PVC around to be used for the recreated Pod: binding the Pod ownerReference to the PVC would delete the PVC in that situation.

```
nodes:
    - nodeCount: 2
      name: testgroup1
      pvcDeletionStrategy: {donotdelete(default), deleteperpod, deleteperstatefulset}
      config:
        ...
``` 

I tend to think it's better to stick with "we delete PVCs that are not needed" for the time being, and do whatever's necessary in the code to handle that. Then if we see it may make sense to keep the PVC around for some use cases, we think about giving that option to the user. Let's avoid adding anything in the Elasticsearch CRD that may be useless or that we may want to change in the future. It's easy to add new fields, but very hard to remove some, for backward-incompatibility reasons.

**Comment by sarjeet2013** [comment]
@sebgl Make sense. Anyways, I have left a comment on the PR itself. Let me know if it make sense?

**Comment by anyasabo** [comment]
>The Elasticsearch resource is removed entirely. In such case, we want to remove all PVCs associated to that cluster. Setting the ownerReference here as suggested by @sarjeet2013 seems to be a very nice trick. However since PVC creation is delegated to the StatefulSet controller, we may need to patch PVCs after creation. Meaning there's a race condition where you could delete the ES resource before we applied the ownerReference.

I'm 99% sure we can set the owner ref to the ES CR in the PVC template, so we should be good here.

**Comment by sarjeet2013** [comment]
>> I'm pretty sure we can set the owner ref to the ES CR in the PVC template, so we should be good here.

@anyasabo Actually No. The ownerReference require the UID which won't exist before ES object is created. Also, Statefulsets configures the volumeClaimTemplates which will not have PVCs being generated until the statefulset get request for a pod which will generate a pvc based on the volumeClaimTemplate (`volumeClaimTemplatename-podname` becomes the pvc name).

Also, the PodTemplate won't have just a single PVC. There can be separate PVC per pod in the statefulset and there can be 10 or 100 pods per statefulsets, hence so many PVCs.

**Comment by anyasabo** [comment]
Right, but the ES object is created before the operator creates the stateful set with the PVC template.

**Comment by sebgl** [comment]
> I'm pretty sure we can set the owner ref to the ES CR in the PVC template, so we should be good here.

Just checked: it works. That's a great idea, it will allow us to get rid of the race condition mentioned above!

@sarjeet2013 the ES object already exists when we create StatefulSets, we can definitely use its UID here. However the StatefulSet object does not exist (yet - since we're creating it), making it harder to bind PVCs lifecycle to the StatefulSet lifecycle. But I think we don't need that: we need a way to remove a PVC is a StatefulSet is downscaled from eg. 5 to 2 nodes anyway.

**Comment by sarjeet2013** [comment]
@sebgl Agree. The current approach works fine. @anyasabo Good suggestion.
