### ISSUE TITLE
Surface Known Error Conditions Through Events

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1478]
Suggested by @idanmo:  identify known error conditions that are currently only logged and consider surfacing them through events. 

* this would improve discoverability of error conditions (over just dumping them in the logs)

**Comment by anyasabo** [comment]
Related: https://github.com/elastic/cloud-on-k8s/issues/1293
We may want to emit an event if the webhook is disabled or bypassed somehow

**Comment by pebrc** [comment]
I would say that all validation errors are a good candidates to be turned into events when run in the main reconciliation loop (which we do as a backup in case the webhook fails or is disabled)

https://github.com/elastic/cloud-on-k8s/blob/58b28fb3a233b0b0ff96ca0c9248b59bd233aadf/operators/pkg/controller/elasticsearch/elasticsearch_controller.go#L249

**Comment by charith-elastic** [comment]
Validation errors are already recorded as events here: https://github.com/elastic/cloud-on-k8s/blob/1d55099d11de6fc7474e0a228d0d3cabd230845c/operators/pkg/controller/elasticsearch/reconcile/state.go#L154

I looked at all the places inside the controller package tree where `log.Error` is called. In most cases, it is used to log what would typically be categorised as warnings (i.e. recoverable errors). We should review these logging statements in a separate issue because the "ERROR" level and the associated stacktrace is probably not necessary in a majority of cases.

Some potentially noteworthy (but rare) errors cannot be converted to events at the origin because they are deep inside the call stack without access to the associated object and the event recorder. However, as a first step, we can simply generate an event inside the main `Reconcile` function whenever it is about to return a non-nil error value. We can then iterate on this implementation to remove noisy events and add more context to important ones.

**Comment by charith-elastic** [comment]
#1578 covers most of the commonly encountered errors. There is some additional work to be done to surface certain (rare) errors. I have created #1811 to track those changes.
