### ISSUE TITLE
Improve handling public CA for ES certificate in Kibana

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#1614]
There are three cases to consider when it comes to ES TLS CA:
1. internal (operators own) CA,
1. external, non-public CA,
1. external, public CA.

Right now we don't handle 3. well (#1583) - since we always overwrite Kibanas CA it loses all public CAs. Right now we would require to provide ca.crt in ES TLS secret with public CA chain, which is not a good user experience.

We should stop overriding CAs when there is no ca.crt specified. This will handle case 3.
Case 2. will work as is, because users are expected to provide ca.crt for their internal CA (#1494).
To not regress in case 1. we would need to add ca.crt with operators CA to ES TLS cert secret.

**Comment by david-kow** [comment]
The alternative solution (possibly a change smaller in scope) would be to always include /etc/ssl/certs/ca-bundle.crt together with the current one for Kibana CA as that setting accepts a list of files.

**Comment by pebrc** [comment]
> always include /etc/ssl/certs/ca-bundle.crt

Sounds interesting, the only downside I could see is that it would prevent users from explicitly disabling the trusted certs

This also outlines a manual workaround: users could just specify 
```yaml
elasticsearch.ssl.certificateAuthorities: /etc/ssl/certs/ca-bundle.crt
```
themselves in the `config` section.

> We should stop overriding CAs when there is no ca.crt specified. This will handle case 3.
Case 2. will work as is, because users are expected to provide ca.crt for their internal CA (#1494).
To not regress in case 1. we would need to add ca.crt with operators CA to ES TLS cert secret.

I think I have a slight preference for this solution as it is more explicit.

**Comment by charith-elastic** [comment]
We allow users to provide their own certificates via [TLSOptions](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-api-reference.html#common-k8s-elastic-co-v1alpha1-tlsoptions) in Elasticsearch, Kibana and APM resources. The user-provided certificates can be one of the following:
1. Certificate bought from a well-known CA
1. Certificate managed by cert-manager (ACME, self-signed etc.)
1. Manually self-signed certificate

In all but the first case, `tls.crt` would contain a certificate chain and we should override the following settings to point to the mounted path of `tls.crt`.
- Elasticsearch
    - `xpack.security.http.ssl.certificate_authorities`
- Kibana
    - `elasticsearch.ssl.certificate_authorities`
    - `server.ssl.certificate_authorities` (optional, probably should be explicitly handled by the user)
- APM
    - `output.elasticsearch.ssl.certificate_authorities`
    - `ssl.certificate_authorities` (optional, probably should be explicitly handled by the user)

For case 1, we should not override the certificate authorities and let the applications use the normal certificate verification flow using the root CAs provided by the OS.

The tricky part here is determining when to override the certificate authorities. In case 2 `tls.crt` would be a certificate chain but there would be a `ca.crt` key containing the same chain as well. In case 3, `ca.crt` may or may not exist and it would be hard to reliably distinguish between case 1 and 3.

The simplest solution here would be to make the `ca.crt` key mandatory for all certificates that require overriding the `*.certificate_authorities` setting in their respective application configurations. This is simpler (configuration by convention) and requires only a slight modification to the workflow of people who want to use manually self-signed certificates (extra steps to generate the CA certificate).  

Alternatively, we could modify the CRDs to add a new field to the `TLSOptions` struct that allows the user to explicitly define the behaviour they prefer. This might be less intuitive to use and we would be committed to maintaining it for a long time due to it being part of the public API.

**Comment by pebrc** [comment]
I am in favour of relying on the `ca.crt` field. While it is not 'standardized' in TLS secrets we are already supporting it for people coming from cert-manager. 

> requires only a slight modification to the workflow of people who want to use manually self-signed certificates 

IIUC there is two cases here:
1. self-signed CA and certs issued by said CA: this is basically equivalent to using something like cert-manager with a self-signed issuer. The `ca.crt` attribute will actually be handy here
2. self-signed cert only, here the cert needs to be added to the certificate authorities so either the user just copies the cert into the `ca.crt` field as well (maybe using some YAML anchors?) or we detect that case and do it for them (probably a bad idea too much magic etc for a bit of convenience)

LMK if I missed something.

**Comment by charith-elastic** [comment]
Cert-manager does the correct thing by populating `ca.crt` with the appropriate trust chain.

Quick-and-dirty self-signed certificates (using methods similar to the one we have [documented](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-custom-http-certificate.html)), will not contain the appropriate `ca.crt` key but all that the users need to do is to duplicate the value of `tls.crt` key into the `ca.crt` key as well. I don't think it's possible to detect this case reliably and perform that step automatically because the layout of the secret would be identical to the case when users provide us with a certificate issued by a well-known CA (`ca.crt` should be left blank in that case)
