### ISSUE TITLE
Upgrading a cluster with OnDelete

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#1662]
I'm not sure that an issue is the right format, this is more a design proposal and a follow up of #1442.

## What we want to do

* To be able to update a Pod even if an other Pod with a higher ordinal is "stuck" in an `Unknown` or `Terminating` state.
* To enable shards allocation when the expected Pods are back

What we eventually want to do:

* Be able to update more than one Pod at a time
* Enable back shards allocation if upgrade is stuck, whatever is happening the user may want to not stay too much time with under-replicated shards

The tricky part is to know which Pod(s) is (are) expected to be upgraded.

## Design and algorithm

To deal with these use cases we would introduce the following components:

* `RestartExpectations`: this is an "in memory" data structure that holds the Pods which are expected to be restarted within a given amount of time (TTL)
* `DeletionStrategy`: deciding which Pods can be deleted could be tricky, we may want to:
  * restart the ones with higher ordinals first
  * restart data nodes before master nodes
  * even if we have reached `maxUnavailable` we may want to give a chance to an unhealthy Pod to be restarted
  * add a safety belt to avoid to delete the last healthy master or break the quorum
  
  The aim of the `DeletionStrategy` is to find the best victim for a given context by applying some priorities and some predicates.
* `DeletionController`:  is a controller that receives some potential victims from the main upgrade function:
  * It finds the `DeletionStrategy` to apply
  * It applies the `DeletionStrategy` to find some victims
  * It actually deletes them using theirs `UID` and updates the `RestartExpectations`
  * Returns the list of the `victims`, this can be used by the caller to know if a new reconcile loop must be requeued.

Algorithm:

1. Get some `potentialVictims` to be restarted and create a list of `healthyPods` which contains all the `Ready` `Pods` (even the ones which are not upgraded yet)
2. Get `restartingPods` from the expected restarting Pods in `RestartExpectations`
3. if `potentialVictims` is not empty:
   1. If `restartingPods` is not empty we need to check if a Pod that is being restarted needs to be restarted again. This is to avoid a situation where, for example, user figured out that Pods will not be able to start because of a configuration issue.
      1. Find `potentialVictim` in `restartingPods`
      2. If found and `potentialVictim.UID` <> `restartingPods.UID` then update `RestartExpectations` with the new `UID` and new Timestamp
      3. Delete `potentialVictim` with `UID`
      4. Return `victims`
   2. If `restartingPods` is empty
      1. Find some `victims` using the `DeletionStrategy`
      2. If `victims` is not empty
         1. Disable shards allocation
         2. Delete `victims`  using theirs `UID` and update `RestartExpectations`
         3. Return `victims`
4. Try to clear `RestartExpectations`, for each `restartingPod` in `restartingPods` find the current one as `currentPod`:
    1. If `currentPod` is not found then check if the statefulset has been downscaled, if `true` then remove Pod from `restartingPods`
    2. If `restartingPod.Timestamp + Timeout > Now` then remove Pod from `restartingPods`
    3. If `restartingPod.UUID != currentPod.UUID && isHealthy(currentPod)` then remove Pod from `restartingPods`

5. If `RestartExpectations` are cleared (empty) enable shard allocation

Notes:

* `isHealthy(pod)`: means that Pod is `Ready` from a K8S point of view and has joined the Elasticsearch cluster.
* Expectations must be cleared before a new batch of Pods can be restarted.
* We have to deal with operator restart, expectations will be lost.

## Concurrent modifications tolerance

We should be able to deal with concurrent modifications:

* statefulset deleted or scaled down
* statefulset updated to fix an issue that prevent a node to start

## Concerns

* We have to deal with operator restart, expectations will be lost. What to do if the operator wake up and find a cluster with shard allocation disabled ? Wait some time, if no Pod are being deleted, enable it back?

**Comment by sebgl** [comment]
Looks good! A few thoughts:

**Expectations**:

I think we can simplify the algorithm a bit if we slightly change the way we use expectations. 

Instead of expecting restarts to happen, I think we can just expect deletions to happen. In memory, we would keep a `expectedDeletions map[clusterName]map[podUUID]struct{}{}`. When we delete a pod, register it in this map. When a pod gets recreated by the sset controller, it gets a different UUID.

At the beginning of any reconciliation attempt for Cluster X, reconcile expectations:
1. Fetch all pods of Cluster X
2. If the number of pods for Cluster X does not match the expected number of pods based on actual StatefulSets replicas, we should requeue (some pods should soon be created or delete by the sset controller).
3. If we expect some pods to be deleted (from UUIDs in the map), but there are still there in the cache, we should requeue (deletion did not happen yet, or is not visible yet in the cache).
4. Clear any UUID in the expectations for which pods don't exist anymore.

Then, the rest of code does not need to care about expectations at all (except when updating them on pod deletion). I think this is good enough to handle restarts: when we deal with the rolling upgrade algo, we **know** that pods we have in the cache are correct. This should remove steps 2, 3.i, and 4 (replaced by the check above).

> What to do if the operator wake up and find a cluster with shard allocation disabled ? Wait some time, if no Pod are being deleted, enable it back?

If the operator restarts, everything would be fine here: it does fetch a fresh version of resources, any deletion we did is visible in the pods we retrieve.

> What to do if the operator wake up and find a cluster with shard allocation disabled ? Wait some time, if no Pod are being deleted, enable it back?

I think we can slightly adapt the [existing mechanism](https://github.com/elastic/cloud-on-k8s/blob/1688398e1914c3c377ea479f3a246a278c1f4422/pkg/controller/elasticsearch/driver/upgrade.go#L268-L318):
* if some pods are currently being restarted, either:
    * they are being deleted (will be recreated soon) - expectations should have catched that and requeued already
    * they are restarted already (and visible in the cache) - that's fine
* all existing pods need to be in the cluster as seen from ES

**Restarting restarting pods**:

> If restartingPods is not empty we need to check if a Pod that is being restarted needs to be restarted again

I think we should always iterate through StatefulSets in the same stable order. We can [sort StatefulSets by alphabetical order, master nodes last](https://github.com/elastic/cloud-on-k8s/pull/1661/files#diff-58cb9b3ee5b3d2e66b12513e5e000b71R69-R86). To know whether a pod needs to be restarted, we just [look at its revision label, and compare it with the StatefulSet updateRevision label](https://github.com/elastic/cloud-on-k8s/blob/1688398e1914c3c377ea479f3a246a278c1f4422/pkg/controller/elasticsearch/driver/upgrade.go#L236). If different, the pod needs to be restarted. Since we always process StatefulSets (and pods within those) in the same order, if a pod we restarted needs to be restarted again (different revision), then we'll restart it before any other pods that isn't restarted yet.

**Comment by pebrc** [comment]
Just some nits about naming: let's not use the word 'victims' sounds like we are committing a crime. And let's reserve the word controller for actual k8s controllers.

**Comment by barkbay** [comment]
@sebgl  thanks for the quick review !

I still need to figure out if I can really simplify the algorithm 😄 , I will work on that.

> I think we should always iterate through StatefulSets in the same stable order.

The point here is to proactively re-restart a Pod that would never restart otherwise (e.g. bad config.). I agree that it could be a side-effect of the described expectations.

**Comment by sebgl** [comment]
Pretty sure we'll find something, also it doesn't have to be perfect at first implementation!

It would be nice to see how this may fit (or not) with expectations in https://github.com/elastic/cloud-on-k8s/pull/1654#discussion_r319000150 (basically need to make sure we don't have master nodes in the process of being created/deleted before adding another one). If we happen to need more generic expectations there that also cover the upgrade case that's probably less code to implement.

Also would be nice if the solution we come up with does also work when the operator restarts with an empty state (**but** an up-to-date cache).

I'm wondering whether the case you describe (`proactively re-restart a Pod that would never restart otherwise `) can be extended to any pod to upgrade that is failing; whether it's from a restart or an upscale or anything. We would restart those first (including ones that failed from previous restart).

**Comment by barkbay** [comment]
I have been working on Seb's idea. If we add a predicate that allow unhealthy Pods _(and only unhealthy Pods)_ to be deleted if the status is **not** green we can get rid of `3.i`

Steps `2` and `4` are replaced by a check of the expectations at the beginning of the upgrade procedure.

The only concern I have is that we wait for all the nodes to join the cluster to enable again shards allocation ... which may never happen _(e.g. bad configuration, nobody pay attention, it may leave the cluster with an under-replicated shard for a long time)_ .
It could be nice to add a timeout here to reenable shards allocation after some times, or we could also say that it is up to the user to fix the situation or manually enable shards allocation ?

I still need to figure out how it matches #1654

**Comment by pebrc** [comment]
> It could be nice to add a timeout here to reenable shards allocation after some times, or we could also say that it is up to the user to fix the situation or manually enable shards allocation ?

I think leaving it to the user sounds like the right thing to do, maybe flagging it up with an event if the nodes don't rejoin after a certain time. 

> I still need to figure out how it matches #1654

I _think_ both algorithms should be fairly independent of each other. For rolling upgrades we don't touch zen1/zen2 discovery settings. So the only overlapping concern I can think of is on very small clusters (<= 3) where removal of a master node combined with restart of another master node might make the cluster drop below quorum temporarily (before it is adjusted). But #1654 adds a check on top of the reconciliation that checks that all pending pod changes are visible to the operator before continuing iiuc which should mitigate that somewhat.

**Comment by barkbay** [comment]
This is confusing, a rolling upgrade may lead to a "master upscale" or a "master downscale". In those cases some zen1/2 settings should be updated as well.

During a rolling upgrade:
* If a node type is unchanged and node is a master: we should do our best to not go bellow the quorum (I think this is the situation you are thinking of)
* If restarting a node leads to a permanent type change then we have to treat those situations as an upscale and a downscale. For example the deletion of a mater _(e.g. MDI updated to DI)_ or the addition of a new master _(DI update to MDI)_ should update the zen1/2 settings of the cluster.

**Comment by pebrc** [comment]
Yes you are right about confirmation changes leading to master node additions or removals. We discussed this case in #1289 it is currently not implemented with partitions

**Comment by barkbay** [comment]
> In memory, we would keep a expectedDeletions map[clusterName]map[podUUID]struct{}{}

I'm wondering if we should not use the pod name as a key and its spec as the value, instead of its `UID` and an empty struct.
Two reasons:

* There is no index by UID internally (see https://github.com/kubernetes/kubernetes/issues/20572#issuecomment-191516958) I know that we already have all the Pods in cache but it feels odd to iterate trough all of them while we could use something more efficient like the namespaced name.
* logs: if expectations are not met we could log at the debug level the name of the Pod(s) we are waiting for, I think it is more user friendly than a UID.

**Comment by pebrc** [comment]
> key and its spec as the value

keeping the whole spec sounds a bit excessive, but otherwise 👍 on having the pod name in there as well to make it easier to debug what is going on. I don't think we will get around the requirement of looping through all the pods in the cluster though even if we have the pod name?

**Comment by barkbay** [comment]
>  I don't think we will get around the requirement of looping through all the pods in the cluster though even if we have the pod name?

Yes you're perfectly right. It sounds like a small improvement as  it will not reduce the overall complexity. But I will try to keep around the pod name for the logs.

**Comment by barkbay** [comment]
Closed by #1683
