### ISSUE TITLE
Kubernetes Ingress & Cert-Manager Support

### ISSUE THREAD

**Issue by MrBones757** [elastic/cloud-on-k8s#1667]
## Proposal

Support Ingress resources for kibana and elasticsearch http external endpoints.

Goal: Use the operator to configure a kubernetes http ingress (nginx in my usecase) to allow external access to the es cluster & kibana. 
This should also enable the use of cert-manager to manage trusted https certs for user interaction rather than using an unsecured connection or self-signed certs generated by the operator. 
This would also provide a simple to configure way for external resources (logstash, fluentd) to utilise the cluster's _bulk endpoint for ingest events.

Benefits of cert-manager: letsencrypt & custom (internal) org CA support & automated maintenance.

I'm not sure if this can be achieved using the existing feature set in 0.9 - I've tried a few things based on existing doco (manipulating tls with external cert-manager certificate resources) but haven't been able to get it to work; so i assume it isn't supported.

**Comment by charith-elastic** [comment]
There are many different ingress implementations and security requirements to consider when it comes to exposing the services externally. We feel that it is best to let the users evaluate the implications carefully and pick what works for them rather than us prescribing a particular way of doing things. 

The documentation provides general instructions about allowing external access and TLS configuration: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-accessing-elastic-services.html#k8s-allow-public-access

As for the particular configuration described in this issue, I believe that it is already possible to use nginx-ingress and Let's Encrypt to expose services to the outside world. See #806 and #1494 for previous discussions around this use case.

**Comment by charith-elastic** [comment]
Closing the issue as there are no actions to be taken. Feel free to reopen if you need further help.

**Comment by MrBones757** [comment]
Thankyou for the information - based on the feedback you provided i have moved to using a LoadBalancer resource rather than an Ingress resource. My question now is around annotations of aforementioned LB resources - looking at the CRD it doesn't look like this is possible - is that correct? I thought it may have been possible based on the validation/openapiv3schema/properties/spec/properties/http/propertoes/service/properties section under the elastic search crd, though i've tried a few configuration and i cant seem to make it work. annotations are never added to the LB Service.

**Comment by charith-elastic** [comment]
You can use the [`serviceTemplate`](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-api-reference.html#common-k8s-elastic-co-v1alpha1-servicetemplate) to add labels and annotations to the service. A very basic example would be:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: hulk
spec:
  version: 7.3.0
  http:
    service:
      metadata:
        labels:
          foo: bar
        annotations:
          baz: qux
  nodes:
  - nodeCount: 1
    name: default
```

```
kubectl get svc hulk-es-http -o='custom-columns=Name:.metadata.name,ANN:.metadata.annotations.baz'
Name           ANN
hulk-es-http   qux
```
