### ISSUE TITLE
Pod readiness based on cluster availability breaks change budget

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1748]
Symptom:
```
2019-09-18T14:09:36.818+0200	DEBUG	driver	Applying predicates	{"ver": "0.10.0-SNAPSHOT-44bf3755", "maxUnavailableReached": true, "allowedDeletions": -1}
2019-09-18T14:09:37.191+0200	INFO	driver	Deleting pod for rolling upgrade	
```

this sequence of events is possible because we allow the deletion of 'unhealthy' pods. Unhealthy is defined as pods being 'ready' in the k8s sense of the word.

The problem is that pod readiness is tied to cluster availability [1]. During a rolling upgrade it is likely to happen that the master node is rolled at some point. If the master election does not happen quick enough (very likely on 6.x clusters) all remaining pods lose the 'ready' state and become fair game for the deletion algorithm. We then delete more pods even though we have already reached our 'maxUnavailable' limit and even though these pods are actually available.

I have not been able to reproduce this with 7.x probably because master election is so much quicker. With 6.x it also quite hard to reproduce but does happen.

[1] so this is a bit counterintuitive and took me while to understand: we request `/` in the health check which will return 503 when the cluster is unavailable during master election. If we were to request something like `_cat/nodes?local` the pod would stay 'ready' during master election. This makes this issue also relevant for #916

**Comment by sebgl** [comment]
Also: if there's a global network glitch in the k8s cluster and nodes cannot reach each other, then it means ECK will suddenly be allowed to rotate them all at once, which is probably not what we want.

We could try to be smarter in the way we decide to rotate or not an unhealthy Pod; but I think we still want to support @barkbay 's idea for this. That is: if a user changes the spec to a wrong configuration that leads to a Pod being unhealthy (eg. bootlooping) we should allow rotating that Pod again with a new spec. Otherwise the user would be stuck here with one unhealthy Pod that we cannot rotate since it's taking all the budget. One way to limit the impact could be to allow only one extra unhealthy pod to be rotated beyond the maxUnavailable budget?

Changing the pod healthcheck as you suggest Peter is maybe the best fix here. Setting #916 aside, I think that's what we wanted to begin with: if the node can responds to requests and serve data, then it can be included in the service. That's favouring availability over consistency though.

**Comment by barkbay** [comment]
> so this is a bit counterintuitive and took me while to understand: we request / in the health check which will return 503 when the cluster is unavailable during master election.

Good catch and agreed. I think I'm 👍 with your idea to change the request.

**Comment by david-kow** [comment]
> Also: if there's a global network glitch in the k8s cluster and nodes cannot reach each other, then it means ECK will suddenly be allowed to rotate them all at once, which is probably not what we want.

:+1:

> Otherwise the user would be stuck here with one unhealthy Pod that we cannot rotate since it's taking all the budget. One way to limit the impact could be to allow only one extra unhealthy pod to be rotated beyond the maxUnavailable budget?

Question: while it is taking the budget it's also free to recycle as it's already unavailable, wouldn't it? Also, I think that whenever possible we should strictly adhere to the limits given by the user. I can imagine it could be hard to explain/defend to users that in some cases we ignore their (very explicit) setting.
