### ISSUE TITLE
Should we remove the settings blacklist and replace it with documentation?

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1760]
We currently blacklist a few settings, mainly to make sure the operator works correctly and users don't accidentally change settings we rely on. 

We could instead document the settings we recommend users to leave alone to guarantee correct operation of the operator (but leave the escape hatch open for users that know what they are doing)

**Comment by sebgl** [comment]
The current behaviour is that users cannot set some settings through the `config:` field in the Elasticsearch spec, but can specify them using environment variable overrides.
In a way, it prevents users to shoot themselves in the foot **unless they really want it**. However, it makes the blacklist inconsistent.

I'm +1 for what @pebrc suggests: don't blacklist any setting, but document the ones ECK set.

**Comment by charith-elastic** [comment]
In either case, we have to maintain a list of reserved settings somewhere. I think we should retain the blacklist in the source code. However, instead of causing the validation check to fail, it should produce log messages (and perhaps events as well). It would help to diagnose problems quickly. 

Without an automated warning system, whoever is troubleshooting the problem has to _know_ that a reserved settings list exists and connect the failure to it. In most cases, it won't be obvious that the failure is due to an unsanctioned config value at all (see #2075)

**Comment by pebrc** [comment]
Log messages and events seems like the best we can do for now. Ideally we would have a way of expressing warnings through API server validations but I think this is not supported at the moment (either pass or fail there is no warning mode)
