### ISSUE TITLE
Separate ES, Kibana and stack e2e tests

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#204]
For now, everything is under the resopnsibility of a stack.
We should separate what's specific to:
- Elasticsearch clusters (ES resource)
- Kibana resource
- Stack resource

**Comment by thbkrkr** [comment]
Since the usual way of deploying resources with the operator is to apply yaml files, I wonder if we should also use only yaml files to define the resources used in the E2E tests, as we do in the smoke test?

https://github.com/elastic/cloud-on-k8s/blob/b6100d7d6ad8e181556b3e1b0586bd296bc74e6c/operators/test/e2e/smoke_test.go#L23
