### ISSUE TITLE
Document beta1 known issues

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2042]
We have three known issues in beta1 so far: 

* https://github.com/elastic/cloud-on-k8s/issues/2037
* https://github.com/elastic/cloud-on-k8s/issues/1984
* https://github.com/elastic/cloud-on-k8s/issues/2034

Let's document them and describe workarounds if applicable until we can ship the next release that fixes them.

**Comment by PaulGrandperrin** [comment]
Hi @pebrc,
Sorry to kind-of-but-not-totally highjack this issue, but there is another issue that I created that was closed I think too early: https://github.com/elastic/cloud-on-k8s/issues/2039
I think this is a legitimate use-case (it's documented in the doc) and also I think the operator should never be stuck so hard because of a syntax error.
Thanks for your time!
