### ISSUE TITLE
APM Server Spec.config does not override the apm-server.yaml

### ISSUE THREAD

**Issue by tomqwu** [elastic/cloud-on-k8s#2050]
## Bug Report
**What did you do?**
Trying to install a quickstart app server from elasticsearchRef, I tried delete apmserver type a couple of times, still no luck

```
apiVersion: apm.k8s.elastic.co/v1beta1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: default
spec:
  version: 7.4.0
  count: 1
  config:
    output:
      elasticsearch:
        headers:
          X-My-Header: Just an example of a custom settings
  elasticsearchRef:
    name: quickstart
```
**What did you expect to see?**
I should expect to see the output config is override by config block

**What did you see instead? Under which circumstances?**
Nothing happens in the `apm-server.yaml`
```
bash-4.2$ cat apm-server.yml | grep -v "#" | awk "NF"
apm-server:
  host: "0.0.0.0:8200"
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
```
**Environment**

* ECK version:

	7.4.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by anyasabo** [comment]
The config file used is in `/usr/share/apm-server/config/config-secret/apm-server.yml`, but going by the output you are probably looking in `/usr/share/apm-server/apm-server.yml`. Are you seeing issues with the actual behavior of the APM server?

I verified that file was being populated as expected by the secret and was being used by the apm server process, so I think we are good here. But feel free to re-open if necessary.


On a related note: it looks like the logs are a little confusing because even if you specify a different config path, it still logs the default one:
```

bash-4.2$ apm-server -e -c config/config-secret/apm-server.yml 
...
2019-10-24T01:36:47.250Z    INFO    instance/beat.go:607    Home path: [/usr/share/apm-server] Config path: [/usr/share/apm-server] Data path: [/usr/share/apm-server/data] Logs path: [/usr/share/apm-server/logs]
```
