### ISSUE TITLE
ECK and ILM 

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2077]
Currently we don't mange ILM actively in ECK. That means there is a potential during downscales that clusters end up with unachievable and contradictory allocation requirements. In particular if ECK decides to delete an Elasticsearch node and ILM decides to allocate all shards of a given index on that node in order to [shrink](https://www.elastic.co/guide/en/elasticsearch/reference/current/_actions.html#ilm-shrink-action) the index. 

A suggested workaround until Elasticsearch handles decommissioning of nodes itself is:
1. ECK decommissions (sets its cluster-level allocation excludes) node (ILM is still running). For these steps, let’s assume that `instance-0003` is the node being removed.
2. While checking shard migration progress, ECK checks for any indices that have `index.routing.allocation.require._id: instance-0003` or `index.routing.allocation.include._id: instance-0003`
3. If an index has either require/include rule for the node being decommissioned, ECK removes the setting (sets it to null)
4. Once ECK has determined decommissioning is finished, it stops ILM with curl -XPOST localhost:9200/_ilm/stop.
5. ECK checks one more time (performing steps 2 & 3) that data has been correctly moved off the node (to avoid a race condition between decommission check and ILM shutdown).
6. ECK removes the node from the cluster.
7. For the indices where the setting was removed by ECK, an ILM explain is performed.
    1. If the index is in the ERROR step, validate that the error occurred in the ‘check-shrink-allocation’ step (this info is present in the ILM explain output). We then perform: `curl -XPOST localhost:9200/_ilm/move/<index> -d’{"current_step": {"phase": "warm","action": "shrink","name": "ERROR"},"next_step": {"phase": "warm","action": "shrink","name": "set-single-node-allocation"}}’`
    2. If the index is in the “check-shrink-allocation” step, we perform: `curl -XPOST localhost:9200/_ilm/move/<index> -d’{"current_step": {"phase": "warm","action": "shrink","name": "check-shrink-allocation"},"next_step": {"phase": "warm","action": "shrink","name": "set-single-node-allocation"}}’`
8. ECK starts up ILM with curl -XPOST localhost:9200/_ilm/start.

Step 7. is problematic as it would require ECK to maintain the state of the indices that have been modified. We could either use annotations on the Elasticsearch resource or just check all indices for error conditions

**Comment by barkbay** [comment]
>  Step 7. is problematic as it would require ECK to maintain the state of the indices that have been modified. We could either use annotations on the Elasticsearch resource or just check all indices for error conditions

I'm not sure that there is a reliable way to know if the ILM lifecycle is in error _(for this particular step)_ because of the operator or for an other reason: error may happen right before ECK sets routing settings to `null`. Thus I'm not sure that there is a real benefit to maintain a persistent state: we could assume that resetting ILM for every indices in error within the `check-shrink-allocation` step is the only thing we can do when ECK is restarted.

In this case we could just keep this information in memory and only do the ILM explain in two situations:

1. At runtime:
   1. Keep in memory the ILM status (started/stopped) and the list indices for which the routing has been altered.
   2. Resume lifecycle management for these indices when node is removed.
2. After a restart of the operator:
   1. If ILM is stopped then start it. We should assume here that any node in a `Terminating` state is still excluded _(is it the case ?)_. We want to avoid a race condition where a node is not yet removed but could be still selected in the `Shrink` action.
   2. Check for all indices if an error occurred in the `check-shrink-allocation` step. Resume lifecycle management for each indices.

**Comment by pebrc** [comment]
We discussed offline:
* Elasticsearch will improve its handling in future versions
* let's not tackle this in ECK unless we would have data loss in existing versions of Elasticsearch (this needs to be verified if this is the case)

**Comment by hprotzek** [comment]
Hi, we had this problem now, several times, when we migrated the ECK nodeSet to bigger disks. The ILM lifecycle got stuck in `shrink` because the target node was one of the older nodes that got removed and we end up with `Waiting for node [jS-cGQXaSMm1ryifkwSPXQ] to contain [10] shards, found [0], remaining [10]`

Is there any work done in ES that will prevent this?

**Comment by pebrc** [comment]
#4597 introduces the Node Shutdown API to ECK and ILM will be correctly managed by Elasticsearch itself through that API.
