### ISSUE TITLE
Elasticsearch stuck in ApplyingChanges

### ISSUE THREAD

**Issue by a-hat** [elastic/cloud-on-k8s#2087]
## Bug Report

**What did you do?**
Added a `secureSettings` section to an existing Elasticsearch resource, as described [in the docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-es-secure-settings.html).

**What did you expect to see?**
The Elasticsearch pods should be configured and restarted, and the keystore should contain the new settings.

**What did you see instead? Under which circumstances?**

Elasticsearch resource is stuck in phase `ApplyingChanges`.

**Environment**

* ECK version: 1.0.0-beta1

* Kubernetes information: EKS 1.14

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Logs:
If found no relevant entries in the operator logs.

**Comment by a-hat** [comment]
Apparently the cause of this problem is that the ES cluster had only one node. I suppose the operator always wants to keep one node running to guarantee the availability of the cluster, which is fine. But with version 0.9 of the operator, the behaviour was different if I remember correctly. The operator spawned another node with the new settings, and finally terminated the old node.

I suppose this is due to the implementation with StatefulSets. Will this behaviour change, or is it intended?

**Comment by sebgl** [comment]
Hey @a-hat, it is intended that we now prefer rolling upgrades (replace nodes one by one) instead of grow and shrink (add a new node then remove the old one).

However, in your particular case, the single node cluster should still be upgraded, temporarily taking down your one-node cluster while the node is being recreated.

Can you share the Elasticsearch yaml manifests, and logs of the operator? There is probably something preventing the upgrade from happening. Does your Elasticsearch cluster have a green health?

**Comment by sebgl** [comment]
> The cluster was in yellow health state, because number_of_replicas was set to 1, and it only had a single node. Could this be the reason why the upgrade did not take place?

Exactly. ECK will refuse to perform a rolling upgrade, for safety reason, if the cluster is not green. Because it would then make your cluster unavailable while the node is being upgraded.

I suggest you either add more nodes or set `number_of_replicas` to 0?

At some point we may want to allow "unsafe" upgrades. I created https://github.com/elastic/cloud-on-k8s/issues/2092.

**Comment by a-hat** [comment]
Yes, makes perfect sense.

Does the operator output a message in the log when it cannot apply the changes to the cluster? If it does, then I missed it. This information would have been very useful.

**Comment by sebgl** [comment]
We log this as debug-level:

```
2019-10-31T12:11:50.545+0100    DEBUG   driver  Predicate failed        {"ver": "1.0.0-beta1-8f70aa99", "pod_name": "elasticsearch-sample-es-default-0", "predicate_name": "do_not_restart_healthy_node_if_not_green"}
```

I'll create an issue to output something in INFO level.
