### ISSUE TITLE
Generic requeue result is ineffective

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#2138]
Due to the fact that:
1. we return specific requeue result for CA expiry, and 
2. `results.Aggregate()` prefers specific result to a generic one (even if it's far in the future)

the generic requeue results are ineffective.  We use them in case of conflicts for status updates and finalizers.

It seems we need to always specify `RequeueAfter`.

**Comment by charith-elastic** [comment]
In the controller-runtime loop, the logic appears to be:
- if `RequeueAfter` is specified, then add the item back to the queue after the specified duration 
- if `RequeueAfter` is 0 but `Requeue` is `true`, add the item to the queue using the rate limiter (the default rate limiter for an item is the exponential rate limiter that adds a delay calculated as `min(5ms * (2^numRequeues), 1000s)`)
- if `RequeueAfter` is 0 and `Requeue` is `false`, forget the item

Based on the tests in `pkg/controller/common/reconciler/results_test.go` I believe the definitions of "specific" and "generic" are as follows:
- `generic`: `{Requeue: true}`
- `specific`: `{RequeueAfter: <duration>}`

In addition, `noqueue` would be `{Requeue: false, RequeueAfter: 0}`.

In the aggregation logic of the `Results` wrapper,  the order of precedence is `noqueue` < `generic` < `specific`. When there are two or more `specific` results, the one with the shortest `RequeueAfter` wins.

If I understand the problem, the `specific` result returned by a CA reconciliation could be months in the future (but explicitly capped to 10 hours maximum) and will take precedence over a `generic` result that would otherwise get re-queued in less than 10 hours. 

Unfortunately, there doesn't seem to be an easy way to get access to the rate limiter in use by the controller to figure out exactly when an item is expected to be re-queued. However, since the maximum delay would be 1000s (~17 minutes), I think that one way to address the issue is to consider `generic` results as having an implicit `RequeueAfter` of 1000s and use that to determine which result should take precedence. 

I am not aware of the specific situation that caused this issue to be raised. @david-kow will the solution I suggest address the original problem you were trying to solve?

**Comment by charith-elastic** [comment]
We could probably use a more optimistic value for the implicit `RequeueAfter` value of generic results. Perhaps something like 1 minute.

**Comment by barkbay** [comment]
What if the priority is changed from `noqueue < generic < specific` to `noqueue < specific < generic`

My understanding is that the `generic` requeue relies on the rate limiter, which is good because it's protecting the operator, so maybe we should give it more priority: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L256-L275

**Comment by charith-elastic** [comment]
That could certainly work but I was wondering whether there might be cases where we do want the re-queuing to be delayed. I guess the root problem is that when there are multiple reconciliation functions involved, there's no obvious way to say which function result is more important than the other.

**Comment by charith-elastic** [comment]
Had a look through the places where the results aggregation is used and I could not see any obvious problems with changing the priority order to `noqueue < specific < generic` as Michael suggested. 

The results aggregation is only strictly required in a couple of places only and the rest of the uses of it can probably be removed from the code base at some point.
