### ISSUE TITLE
Want to confirm, the current default configuration is to set memory locking to false?

### ISSUE THREAD

**Issue by ftyuuu** [elastic/cloud-on-k8s#2149]
Like title, How does eck handle memory locking?

**Comment by barkbay** [comment]
I guess you are making reference to [this Elasticsearch feature](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#bootstrap-memory_lock). ECK does not change this setting, you can set it [following this documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-node-configuration.html)

That said IIRC Kubelet fails to start if swap is enabled, so having some memory pages swapped out is unlikely to happen.

Please use https://discuss.elastic.co/c/eck instead of Github issues if you need more information.

**Comment by ftyuuu** [comment]
@barkbay thanks!!!
