### ISSUE TITLE
Create scale testing harness

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#2154]
To facilitate scale testing of ECK, we require the following:
- an instrumented cluster
- mechanism to create a large number of ECK resources and monitor them

Related to #357

**Comment by charith-elastic** [comment]
Initial prototype is here: https://github.com/elastic/eck-utils

**Comment by david-kow** [comment]
This looks nice! I didn't look super closely yet, but I have two questions:
1. > The eck-harness utility creates copies of ECK resources until no more healthy instances can be created. 

Are you thinking about adding other scenario types? I might be wrong, but my feeling is that this will be always constrained on cluster resources and not on operator itself since (IIUC) operator will provision, then wait, then provision, then wait, etc.

2. Why terraform for cluster provisioning? Would implementing whatever is missing from deployer be more expensive than having two ways to provision clusters (one for e2e tests and one for scale tests)?

**Comment by charith-elastic** [comment]
1. This is the foundational step and my intention is to establish a simple baseline for further tests. I have other scenarios in mind (eg. chaos testing) that might require a future refactoring to accommodate. 
Since we are working on top of Kubernetes, the ceiling is well defined by the limitations of Kubernetes itself. Even if we could do better, it wouldn't make much sense. The idea here is to have an automated way of spawning instances until either the operator fails or we hit a Kubernetes limit. The former is interesting and should be documented/investigated while the latter is expected behaviour and not exactly noteworthy. 

2. The scale testing cluster is a bit more complicated than the E2E cluster and it is much easier to use a declarative tool like Terraform to define it as it doesn't require figuring out the correct CLI invocations and writing code to execute them. It also has a large number of reusable modules, built-in templating, error handling, dependency graphs, and a stateful, diff-based apply mechanism that is very useful for applying incremental changes and recovering from errors.

**Comment by david-kow** [comment]
I appreciate Terraform's long list of features, nevertheless I think we should default to a single solution for doing the same thing, if possible.

Regarding 1., I was referring to something else :) but I think we are on the same page with further testing, so :+1:

**Comment by charith-elastic** [comment]
> I appreciate Terraform's long list of features, nevertheless I think we should default to a single solution for doing the same thing, if possible.

The point I was trying to make was that adapting the deployer to this use case would have required a lot more additional work and ultimately resulted in a poor approximation of Terraform that we would have to keep on maintaining ourselves indefinitely. It wasn't an indictment of the deployer -- which is quite adequate for the relatively static use case of creating E2E test clusters.  Apologies if it came across as such.

**Comment by barkbay** [comment]
I just did a few tests with the terraform manifests. I have opened [https://github.com/elastic/eck-utils/issues](some tickets in the dedicated project).

I think that technically it is really good, I have some concerns about the complexity of the tools.

I have tried to summarize my thoughts below:

## Architecture

IIUC we are relying on 3 main dependencies to setup a cluster:

* Terraform
* Helm
* An external terraform plugin: https://github.com/banzaicloud/terraform-provider-k8s

A few thoughts:

* Helm: do we need really need it ? IIRC Helm helps to manage the lifecycle of complex applications with dependencies by separating them into packages (charts). My feeling is that we are not in that case, if some customization is needed then could we use something "lighter" like Kustomize? It already comes with `kubectl` and we are already using it.

* Terraform: I agree that Terraform is a great tool, really powerful, but it drags its own complexity. Maybe it could be challenging for a dev team to manage an other language and deals with new kinds of problem. I think that a part of the rational behind the "deployer" is that we need a tool to setup an environment but we don't need to manage the full lifecycle of a cluster. Hence the overall complexity of Terraform might not be needed. I have no strong opinion, maybe we could try to understand how hard it would be to improve the deployer so we can share the tradeoffs of each solution ?

* GKE Autoscaling: does it mean that the performance of the operator depends on the performance of Google to create some new nodes?

## Monitoring and metrics

* Hosting the tools on the same cluster: it is usually considered as a "bad practice", it may introduce some noise, even on dedicated nodes because we are still sharing some resources like the network or the control plane. We should try to setup a cluster with the minimum set of tools deployed, or check if we can to follow some ideas described [here](https://github.com/prometheus/prometheus/issues/4633)

* Dog fooding: do we need Prometheus ? Could we use some beats to forward the metrics to an external Elasticsearch instance (managed by ECK) ? We could have one dedicated cluster for all the metrics, with data available for all the team. It would survive cluster deletion and would allow us to compare metrics over the time.

**Comment by charith-elastic** [comment]
Thanks for the thorough review. First of all, I just want to make it very clear that I did not intend this to be _the_ solution and be adopted by the whole team going forward. This is all throwaway code despite the official sounding repository name. That's the main reason why I did not solicit opinions from the rest of the team about technology choices because my main goal was to understand the problem and get some initial results as this is the first time I have been asked to load test a Kubernetes operator. The problem space, measurements, techniques and tools are vastly different from typical load testing scenarios I am familiar with and I wanted to investigate them quickly and efficiently without spending too much time worrying about processes.

To answer your concerns:

- Helm is not just for complex applications. It makes it very easy to package an application for deployment and  most of the popular tools are readily available as Helm charts. Even though Kustomize is an alternative, it lacks a rich ecosystem that can help to get things done quicker.  Also, Terraform natively supports Helm -- which made it easier for me to bootstrap the cluster with the applications I wanted already installed.
- As mentioned above, the use of Terraform in this particular case was purely for convenience and speed. Personally, I am strongly against reinventing the wheel without a good reason but that's a discussion for another time as this meant to be throwaway code and I am not advocating that the whole team immediately adopt Terraform at this point.
- I don't think autoscaling is a concern because it doesn't make much sense to measure how quickly the operator can provision a cluster. Latency is probably not a major concern in infrastructure operations.
- I agree that hosting the tools in the same cluster being tested is not advisable. However, as this is not a typical load test, usual concerns like latency spikes from external interference does not apply here. In fact, most real world deployments will have monitoring tools and other applications sharing the same Kubernetes cluster as the operator. Therefore, I think that the test results would be much more realistic with this setup.
- I went with Prometheus and Grafana because they are already well integrated with Kubernetes and come with many pre-built dashboards to monitor the cluster components. I am certain that the Elastic products are on-par -- if not better -- but, it would have taken too much time and additional work to set them up for this experiment. I was optimizing for time and effort in this case well.
