### ISSUE TITLE
metadata.resourceVersion: Invalid value: 0x0: must be specified for an update"

### ISSUE THREAD

**Issue by ftyuuu** [elastic/cloud-on-k8s#2200]
I write a new crd to reconcile the resource of Elasticsearch, but when i want to update Elasticsearch, it throw a bug as title. And i debug the code, and find that the expected's resourceVersion is empty, so it make reconciled's resourceVersion empty. But i debug the eck code, the fuction of ReconcileStatefulset is same as my code, the resourceVersion of Reconciled in "err := params.Client.Update(params.Reconciled)" is also empty. So how should i do?

```
func ReconcileElasticsearch(
	c k8s.Client,
	scheme *runtime.Scheme,
	nes nesv1beta1.NesCluster,
	expected elasticsearchv1beta1.Elasticsearch,
) (elasticsearchv1beta1.Elasticsearch, error) {

	var reconciled elasticsearchv1beta1.Elasticsearch
	err := reconciler.ReconcileResource(reconciler.Params{
		Client:           c,
		Scheme:           scheme,
		Owner:            &nes,
		Expected:         &expected,
		Reconciled:       &reconciled,
		NeedsUpdate: func() bool {
			if len(reconciled.Labels) == 0 {
				return true
			}
			return !hash.EqualTemplateHashLabels(expected, reconciled)
		},
		UpdateReconciled: func() {
			expected.DeepCopyInto(&reconciled)
		},
	})
	return reconciled, err
}

```

**Comment by sebgl** [comment]
@ftyuuu I'd be interested in knowing more about you're use case (`a new crd to reconcile the resource of Elasticsearch`).

Based on what you said, if that can help:
- the expected resource does not contain any resource version: that's alright
- the actual resource (the one you retrieve from the apiserver - done behind the scenes here in `reconciler.ReconcileResource `) should have one though, so when you update it should be there.

You should probably not use `expected.DeepCopyInto()` in your `UpdateReconciled()` since it erases the existing actual resourceVersion. Instead you may want to do something like:
```
reconciled.Spec = expected.Spec
````

Looking at our codebase I think we do use it for reconciling Kibana deployments and Elasticsearch StatefulSets. According to https://github.com/kubernetes/kubernetes/issues/70674#issuecomment-436737939 it is OK for Deployments but not for many other resource types.

I'm closing since this is not related to ECK.

**Comment by ftyuuu** [comment]
@sebgl Thank you very much for your reply!
