### ISSUE TITLE
User provided credentials for Stack applications

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#2316]
It appears that some users want to restrict the operator to use a specific set of credentials to access Elasticsearch (see https://discuss.elastic.co/t/credentials-for-elastic-operator/212628).

In order to support this scenario, we will have to give the users a way to specify replacements for `elastic-internal`, `elastic-internal-probe`, `elastic-internal-keystore` and `elastic` accounts. 

Currently it is possible to specify the passwords for the operator accounts by manually creating the `<cluster>-es-internal-users` and `<cluster>-es-elastic-user` secrets before creating a cluster but the usernames are fixed and cannot be changed.

**Comment by pebrc** [comment]
The original discussion that prompted this issue to be created was about disabling security in the cluster which is not a use case we want to support. We have since improved file realm support and all user passwords can already be set through the file realm without the need to create secrets ahead of time.  See also https://github.com/elastic/cloud-on-k8s/pull/5613
