### ISSUE TITLE
Add liveness Probe to both Kibana and Elasticsearch pods

### ISSUE THREAD

**Issue by primeroz** [elastic/cloud-on-k8s#2513]
## Proposal

Unless there is a reason for not having one it would be good to have a default livenessProbe configured for both workloads to identify when a pod is stuck and need restarting.

This would also be useful for people, like me , who have admission webhook to check for this policy to be set and have to whitelist workloads that do not have it.

In my pre-ECK elastic stack i just used a tcp socket check on 9300 and 5601 while using a similar check to the one the ECK use for readiness.

**Comment by charith-elastic** [comment]
I am not sure whether adding liveness probes by default will be acceptable for all users because it could have an adverse effect on certain workloads. Since Kubernetes has no understanding of Elasticsearch cluster topology and would blindly restart any pod failing the liveness check, you could easily get into a situation where the cluster becomes unstable or risk losing data depending on how the cluster is configured. 

If you are aware of the possible issues and still prefer to have a liveness check, it can be enabled in the `podTemplate` of Elasticsearch [node sets](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elasticsearch-k8s-elastic-co-v1.html#elasticsearch-k8s-elastic-co-v1-nodeset) and Kibana [spec](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-kibana-k8s-elastic-co-v1.html#kibana-k8s-elastic-co-v1-kibanaspec). The procedure is almost identical to how [readiness probes are configured](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-readiness.html),

**Comment by primeroz** [comment]
I undestand your concerns and it make sense. 

Sure that a liveness probe that can detect proper state of the process (  just establishing a socket on tcp/9300 is probably not good enough ) should not cause issues to any cluster because a process that can't establish sockets on 9300 can't really be part of a cluster ... so , imho, a blind restart of such a pod is , from an elasticsearch cluster topology perspective, still better then a stuck pod that is not part of a cluster but is also not being replaced.

Does the operator do any _monitoring_ of individual pods and their state as part of the cluster ?

**Comment by charith-elastic** [comment]
The operator does have to consider the state of the cluster and individual nodes within it when [upgrading or scaling clusters](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-orchestration.html). However, it does not try to automatically heal the cluster by restarting unavailable nodes because there are many edge cases to consider and it's safer to defer that decision to the user. (The fault detection logic in Elasticsearch itself should be able to gracefully deal with most cases of unavailable nodes anyway).

While restarting a node might be the solution to certain types of problems, there's no guarantee that it is the right action to take on every instance. In fact, blindly restarting nodes without understanding the root cause could end up exacerbating the problem. This is why the operator does not apply a default liveness check and leaves that decision up to the user.

**Comment by primeroz** [comment]
I understand.

I will for now deal with this situation by myself in the PodSpecs 

Maybe while the project mature there will be some space at some point to look at handling some of the pod health situations.

thanks!
