### ISSUE TITLE
User-provided Elasticsearch config overrides should have precedence over ECK config

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2573]
Currently, users get a warning if they specify an Elasticsearch config field already handled by ECK.
However, our philosophy is to still allow power users to achieve what they want.

When reconciling the user-provided configuration with the ECK-generated configuration, we do not currently give priority to the user-provided configuration:

https://github.com/elastic/cloud-on-k8s/blob/f63396e905a2fbaa5f5746fc9655044bddf400f5/pkg/controller/elasticsearch/settings/merged_config.go#L29-L36

This impacts the way users can set multiple volumes for `path.data`: https://discuss.elastic.co/t/how-to-define-multiple-path-data-pointing-to-separate-volumes-or-pvc-using-eck/218644

**Comment by thbkrkr** [comment]
That makes sense, especially since we implemented this behaviour for Kibana and APM Server.

However, I wonder if we should emit a warning or document (generate) the list of settings _normally_ managed by ECK. I fear that a user may remain in the dark for a long time because he shot himself in the foot by overriding an important settings from an ECK perspective.
