### ISSUE TITLE
Add E2E tests for Elastic Stack 8.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#2608]
This depends on https://github.com/elastic/cloud-on-k8s/issues/2607.

**Comment by pebrc** [comment]
I ran a quick smoke test when working on #2607. While APM Server and Elasticsearch tests where succeeding, I ran into trouble with Kibana due to an optimize run that was triggered (and I don't know yet what triggered that). Will focus on #2565 to get the necessary changes merged before returning to this.

**Comment by sebgl** [comment]
Depends on https://github.com/elastic/cloud-on-k8s/issues/2791.
