### ISSUE TITLE
We should allow volume claim templates modifications

### ISSUE THREAD

**Issue by mtparet** [elastic/cloud-on-k8s#2639]
## Proposal

Allow modification of `requests storage` so we could increase disk size without needed create new elasticsearch node and transfer all the data (which in some cases is not a good thing when you have several TB)

Perhaps we could configure the operator to authorize it or not.

## Context

Almost all kubernetes providers allow resizing disk through PVC modifications. Sometimes there is a need to delete pod to be able to do it offline (volume unmounted) but it should a details.

## What is happening today

Today when changing requests storage, the webhook refuses to validates the changes: `Volume claim templates cannot be modified`

**Comment by sebgl** [comment]
Closing as duplicates https://github.com/elastic/cloud-on-k8s/issues/325.

The immutable VolumeClaimTemplates are a [limitation of StatefulSets in Kubernetes](https://github.com/kubernetes/enhancements/pull/660). If we remove the warning on ECK side, StatefulSets reconciliation will still fail with an error since it's impossible to update existing StatefulSets' VolumeClaimTemplates.

https://github.com/elastic/cloud-on-k8s/issues/325 describes the current workaround which involves copying data to volumes in new StatefulSets.

Let's continue the discussion (if any) in https://github.com/elastic/cloud-on-k8s/issues/325.

**Comment by mtparet** [comment]
Sorry for the duplicate, I should have better searched through the existing issues. I look at the original issue.
