### ISSUE TITLE
ElasticSearch fails to be deployed with Istio 1.5

### ISSUE THREAD

**Issue by irizzant** [elastic/cloud-on-k8s#2770]
## Bug Report
**What did you do?**

I tried to deploy the operator using the instructions reported [here](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-service-mesh-istio.html) to enable Istio 1.5 with it.
I know the install procedure claims that it was tested on Istio 1.4.3 but the annotations included apply to the latest Istio version too.

**What did you expect to see?**
Operator + ElasticSearch + Kibana pods running

**What did you see instead? Under which circumstances?**
I managed to get to [this step](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-service-mesh-istio.html#k8s-service-mesh-istio-stack-connection) successfully, the operator pod starts successfully.

After deploying the ElasticSearch cluster, ElasticSearch pods start failing with:
```
2020-03-25T14:15:56.502453Z     info    Proxy role: &model.Proxy{ClusterID:"", Type:"sidecar", IPAddresses:[]string{"172.17.0.14", "172.17.0.14"}, ID:"elastic-istio-es-default-1.elastic-system", Locality:(*envoy_api_v2_core.Locality)(nil), DNSDomain:"elastic-system.svc.cluster.local", ConfigNamespace:"", Metadata:(*model.NodeMetadata)(nil), SidecarScope:(*model.SidecarScope)(nil), MergedGateway:(*model.MergedGateway)(nil), ServiceInstances:[]*model.ServiceInstance(nil), WorkloadLabels:labels.Collection(nil), IstioVersion:(*model.IstioVersion)(nil)}
2020-03-25T14:15:56.502458Z     info    PilotSAN []string(nil)
2020-03-25T14:15:56.502460Z     info    MixerSAN []string(nil)
2020-03-25T14:15:56.502782Z     info    Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 2
configPath: /etc/istio/proxy
connectTimeout: 10s
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
envoyAccessLogService: {}
envoyMetricsService: {}
parentShutdownDuration: 60s
proxyAdminPort: 15000
serviceCluster: elastic-istio-es-default.elastic-system
statNameLength: 189
tracing:
  zipkin:
    address: zipkin.istio-system:9411

2020-03-25T14:15:56.502801Z     info    JWT policy is first-party-jwt
2020-03-25T14:15:56.502985Z     warn    Missing JWT token, can't use in process SDS /var/run/secrets/kubernetes.io/serviceaccount/tokenstat /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
2020-03-25T14:15:56.503001Z     fatal   Missing JWT, can't authenticate with control plane. Try using plain text (15010)
```

It looks like this is due to `automountServiceAccountToken: false` as shown [here](https://github.com/istio/istio/issues/22193).

Also, Kubernetes `Service`'s are not compliant with Istio requirements.
Example:
```
$ istioctl analyze -n elastic-system
Info [IST0118] (Service elastic-webhook-server.elastic-system) Port name  (port: 443, targetPort: 9443) doesn't follow the naming convention of Istio port.
```
But also 
**Environment**
minikube version: v1.8.2
commit: eb13446e786c9ef70cb0a9f85a633194e62396a1
 
* ECK version:
1.0.1 deployed with:
```
$ kubectl apply -f https://download.elastic.co/downloads/eck/1.0.1/all-in-one.yaml
```

* Kubernetes information:
	* On premise ? Yes
	* Cloud: GKE / EKS / AKS ? No
	* Kubernetes distribution: Openshift / Rancher / PKS ? 
minikube version: v1.8.2
commit: eb13446e786c9ef70cb0a9f85a633194e62396a1
	
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by charith-elastic** [comment]
`automountServiceAccountToken` defaults to `true` unless it is overridden by the pod spec or the service account. I can't find any documentation on whether minikube overrides this default so it is unclear why this happened. I recently tested Istio 1.5 with ECK on GKE and did not run into this issue so it has to be an environmental problem. In the mean time though, you can work around this by explicitly setting `automountServiceAccountToken` to `true` in the pod template:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.6.1
  nodeSets:
  - name: default
    count: 3
    podTemplate:
      spec:
        automountServiceAccountToken: true 
```

Thanks for pointing out the issue with the webhook service. In our experiments, the missing name in the webhook service did not have an effect on the correct operation of the operator. However, it's something that's worth fixing so I'll create an issue for it.

**Comment by irizzant** [comment]
Hello
thanks for the reply.
I wanted to point out that following [this](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-service-mesh-istio.html) procedure leads to `automountServiceAccountToken=false` and not true.

**Comment by charith-elastic** [comment]
> I wanted to point out that following [this](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-service-mesh-istio.html) procedure leads to `automountServiceAccountToken=false` and not `true` as a default.

Can you elaborate which part causes the `automoutServiceAccountToken` default value to be changed? That has not been my experience.

**Comment by irizzant** [comment]
I followed the instructions reported [here](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-service-mesh-istio.html):

1. kubectl create ns elastic-system
1. kubectl label namespaces elastic-system istio-injection=enabled
1. kubectl apply -f https://download.elastic.co/downloads/eck/1.0.1/all-in-one.yaml
1. cat << EOF | kubectl -n elastic-system apply -f-
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-istio
spec:
  version: 7.6.1
  http:
    tls: 
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        annotations:
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300" 
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
EOF
1. kubectl -n elastic-system get -o yaml po elastic-istio-es-default-0 | grep auto
  automountServiceAccountToken: false

**Comment by charith-elastic** [comment]
As I said before, the issue you ran into is most likely due to an environmental factor such as a non-standard configuration. Minikube seems to switch off certain feature gates that are normally expected to be switched on and the user has a lot of control over how the Kubernetes cluster is setup as well. Unfortunately, we can't anticipate all possible configuration combinations when writing documentation so the content is created to target the most common configuration that users are likely to have.

Thanks for reporting the issue. We will continue to  review the documentation based on reports such as yours.

**Comment by irizzant** [comment]
@charith-elastic so are you suggesting that the manifests generated with ElasticSearch CRD do not contain any `automoutServiceAccountToken` directive and so they assume the Kubernetes default value?

**Comment by charith-elastic** [comment]
Apologies, @barkbay pointed out to me that ECK does explicitly disable it. It wasn't an issue for me when testing Istio though -- which is very odd. I'll investigate.

**Comment by charith-elastic** [comment]
It appears that the reason is that Minikube does not enable the `TokenRequest` feature gate by default (since Kubernetes 1.12, it is normally enabled by default). If `TokenRequest` is enabled, Istio uses it by default as it considers that more secure than service account tokens (https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens). In the absence of the feature, Istio falls back to service account tokens -- which are disabled by default on ECK-managed resources. 

I will update the documentation to point out this fact for other minikube users. Thanks for bringing it up.

**Comment by irizzant** [comment]
I'm afraid it's not that simple.
As you said TokenRequest feature gate is enabled by default since Kubernetes 1.12 and it's enabled in minikube as well (I'm running the last minikube version which uses Kubernetes 1.17).

The Istio official doc is misleading under this point of view, the check they ask to perform:
```
$ kubectl get --raw /api/v1 | jq '.resources[] | select(.name | index("serviceaccounts/token"))'
{
    "name": "serviceaccounts/token",
    "singularName": "",
    "namespaced": true,
    "group": "authentication.k8s.io",
    "version": "v1",
    "kind": "TokenRequest",
    "verbs": [
        "create"
    ]
}
```
is used to inspect the service account token, not to verify that the TokenRequest feature gate is active.
The subject here is that minikube doesn't support third-party JWT tokens, and it doesn't for a reason: it requires BoundServiceAccountTokenVolume feature gate which is still in alpha.

**Comment by charith-elastic** [comment]
> is there a reason not to set it to `true`

It is considered unsafe because any compromised pod would get access to the API server if RBAC is not properly configured. See https://github.com/kubernetes/kubernetes/issues/57601.

Since this problem only manifests if you run Istio and ECK on Minikube (essentially a non production setup), and because it can be easily addressed by adding a single line to the pod template, I don't think it warrants a change to the current behaviour of ECK.

**Comment by irizzant** [comment]
> It is considered unsafe because any compromised pod would get access to the API server if RBAC is not properly configured. See kubernetes/kubernetes#57601.

RBAC is nowdays, as a matter of fact, enabled everywhere and if it's not configured properly the possibility to get control of a pod is probably the last of the problems.
With RBAC on, an attacker can only authenticate with the API server but couldn't do anything.
Also, a ServiceAccount used by the attacker can be revoked anytime.
Finally using unprivileged users for the Pod would also prevent the attacker to do any other damage.

> Since this problem only manifests if you run Istio and ECK on Minikube (essentially a non production setup), and because it can be easily addressed by adding a single line to the pod template, I don't think it warrants a change to the current behaviour of ECK.

I totally agree on the fact that enabling  `automoutServiceAccountToken` is allowed and easy to perform, but the problem is not minikube related at all. 
Indeed, before opening the issue I originally had it in our Kubespray production cluster.
Any cluster without Service Account Token Volume Projection enabled by default will have this issue.

**Comment by charith-elastic** [comment]
I agree with you in general, but, not all users are going to have an airtight access control configuration. Until the intrusion is detected, the attacker will have all the privileges associated with the compromised pod within the cluster. I think our stance here is that since the current behaviour works in a majority of cases, there's no compelling reason to change it to a slightly insecure  configuration (however insignificant it may be). Of course, some combinations of third-party software and Kubernetes cluster configurations will require users to toggle this feature on in the manifest. It will be a conscious decision on the part of the user so they will have the chance to consider the implications themselves.
