### ISSUE TITLE
make check-requisites produces garbled output

### ISSUE THREAD

**Issue by jhalterman** [elastic/cloud-on-k8s#3052]
The `make check-requisites` target seems to work well but produces somewhat garbled output currently:

<img width="411" alt="Screen Shot 2020-05-12 at 3 41 13 PM" src="https://user-images.githubusercontent.com/228804/81754556-5794c300-946b-11ea-8bdd-f52182df0828.png">

**Comment by anyasabo** [comment]
I messed this up when fixing all the shellcheck warnings. That said, this is only used in `dev-setup.md` that I can see. I think it may make more sense to just link to installers rather than maintain this? I am not sure how useful it is. If other people think it's useful though I'll go ahead and fix it since it was my mistake.

**Comment by jhalterman** [comment]
It's a useful little util, but I suspect linking to the installers is fine if presented in a concise list of prereqs.
