### ISSUE TITLE
Custom certificates in 1.1 may always require CA

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#3082]
Our [docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-tls-certificates.html#k8s-setting-up-your-own-certificate) indicate that custom certificates issued by well known CAs do not need a CA chain provided. A user in [discuss](https://discuss.elastic.co/t/ssl-handshake-fails-between-kibana-apmserver-and-elasticsearch-after-custom-certificate-setting-on-elasticsearch/208604/17?u=anya_sabo) noted that in 1.0 we were not setting the `ssl.certificateAuthorities` field in Kibana, but in 1.1 we do. This was breaking a configuration where the secret did not contain a `ca.crt` key, and instead the CA chain was contained in `tls.crt` along with the actual certificate. They report that this worked in 1.0 but not in 1.1. It may be worth investigating if this is a regression.

**Comment by barkbay** [comment]
I just upgraded a private cluster on which I'm using a Let's Encrypt certificate and I confirm that upgrading from 1.0 to 1.1.1 broke the connection between Kibana and ES.

**Comment by barkbay** [comment]
Since https://github.com/elastic/cloud-on-k8s/issues/2243#issuecomment-564602647 the internal ca is always set. I think this lets the association controller think that the CA cert is provided and should be used in the Kibana or APM configuration: 

https://github.com/elastic/cloud-on-k8s/blob/d281b62588d1860263f3faa65ed8e1b6193ed7ea/pkg/controller/common/association/ca.go#L65-L66
