### ISSUE TITLE
Document ECK install process for air-gapped environments

### ISSUE THREAD

**Issue by n0othing** [elastic/cloud-on-k8s#3416]
## Proposal

Provide a section in the docs that walks users through offline/air-gapped installs of ECK using a private Docker registry.

**Use case. Why is this important?**

Production environments might not have internet access, so having a guide for offline installs would be helpful.

**Comment by pebrc** [comment]
A few starting points for a doc chapter:
* user will have to adjust the install manifests/Helm charts that we provide
   * use `container-registry` flag in https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-operator-config.html to point to their air-gapped container registry
   * optionally turn telemetry off (won't work anyway in an air-gapped environment) 
   * provide images for the operator and all Elastic stack applications they want to run in said registry, make sure that image names and paths match the official ones so that users don't have to spec each image explicitly when using it
   * deploy the operator with using the operator image from the private registry
