### ISSUE TITLE
Add SAML + ECK documentation

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#3433]
There's not much special about configuring SAML on ECK, but questions come up often enough it might be useful to have a specific docs page on how to put the pieces together. Off the top of my head:
- link to ES SAML docs
- our secure settings docs
- that the file realm needs to stay enabled for ECK to function
- there's this SAML troubleshooting doc: https://www.elastic.co/guide/en/elasticsearch/reference/current/trb-security-saml.html
- you can generate the [service provider metadata](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/saml-metadata.html) by kubectl execing in

**Comment by jasonslater2000** [comment]
a few additional ideas I would love to see covered in a doc:

1. how to add & reference a file, e.g. idp_metadata.xml, to the ECK cluster YAML
2. how to add & reference or otherwise configure role mappings declaratively as part of cluster YAML
3. clarification of whether sp.acs should be KIBANA_URL/api/security/saml/callback or KIBANA_URL/api/security/v1/saml - asking because docs say the latter was deprecated in 7.5, yet I just set up a 7.8 ESS cluster with the latter and it works fine.

**Comment by jasonslater2000** [comment]
also suggest including (since i have hit these things myself)
- "Audience URI" vallue must match, vebatim, ES value "sp.entity_id"
- idp.metadata.path can be a URL, e.g. "https://dev-846548.okta.com/app/exkjsqqwtAY1Ykj354x6/sso/saml/metadata"
- checking the metadata XML contents to verify that the value of entityID is the same as "idp.entity_id"

**Comment by briantopping** [comment]
Hi, I was just tasked with discovery on adding SAML to an ECK instance using the operator and I'm afraid I'm about to ask the same questions.

To document my experience, I initially looked at the `Elasticsearch` CRD in more depth and couldn't find anything. My sense was that there must be an `xpack` that I needed to define as some kind of `Any` object on the `Elasticsearch` CR, but I couldn't find that either. 

I do see reference to [you can generate the service provider metadata by kubectl execing in](https://github.com/elastic/cloud-on-k8s/issues/3433#issue-656654416), but my opinion is an instance should be fully configured at the declarative level. To automate such a setup in IaC, we'd otherwise have to revert back to something like Ansible and that would be difficult to track with GitOps. 

Could some kind soul help me see what I am missing here?

**Comment by briantopping** [comment]
Hi @anyasabo, is there anything I can do to assist here?

**Comment by jasonslater2000** [comment]
@briantopping just saw your questions.  are you looking for a way to set options in your kubernetes yml which would otherwise be specified in elasticsearch.yml ?

**Comment by briantopping** [comment]
Thanks @jasonslater2000, we're looking for a way to specify the SAML options without modifying the ephemeral pods that are instantiated by the operators, such as a part of the `Kibana` custom resource.

**Comment by briantopping** [comment]
Recommending to the client at this point they go with the professional version of the Elastic tools.

**Comment by framsouza** [comment]
I just wrote down this doc/how-to setup [SAML on ECK](https://github.com/elastic/support-knowledge-articles/issues/1751)

**Comment by minesskylineGTR** [comment]
> I just wrote down this doc/how-to setup [SAML on ECK](https://github.com/elastic/support-knowledge-articles/issues/1751)

404 on the link. Is it private?

**Comment by framsouza** [comment]
hey @minesskylineGTR this is our support-knowledge-articles repo, I also have it [here](https://github.com/framsouza/eck-saml-hot-warm-cold)

**Comment by alaudazzi** [comment]
@pebrc and I considered the opportunity to reuse some of the content from the [blog post](https://www.elastic.co/blog/how-to-configure-elastic-cloud-on-kubernetes-with-saml-and-hot-warm-cold-architecture) on how to configure SAML and concluded that:
- Some of this blog content can be reused to create a new topic on how to configure SAML
- The new topic should reference the existing SAML docs in ES
- Needs to integrate what is needed for ECK

**Comment by alaudazzi** [comment]
Notes from the meeting with @idanmo:
1. Create a new topic titled “How to configure SAML on ECK”
2. Store it in the Advanced topics section (?)
3. Reference the ES docs: https://www.elastic.co/guide/en/elasticsearch/reference/7.12/saml-guide-stack.html
4. Extract the relevant parts from the [blog](https://www.elastic.co/blog/how-to-configure-elastic-cloud-on-kubernetes-with-saml-and-hot-warm-cold-architecture):
    - Creating a ConfigMap
    - Volume SAML metadata
    - Create SAML ConfigMap
5. Add a working example without specific references

**Comment by alaudazzi** [comment]
An initial draft is [here](https://docs.google.com/document/d/1KX2-EVpD1KuMblUC68E7RsHJl_U2Nd_zqHZiLVFlCAI/edit).

**Comment by idanmo** [comment]
Docs are available [here](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-saml-authentication.html).
