### ISSUE TITLE
ECK documentation version 1.2 not available, broken link for master version

### ISSUE THREAD

**Issue by druesendieb** [elastic/cloud-on-k8s#3449]
## Bug Report
**What did you do?**
Starting from [here](https://www.elastic.co/guide/en/cloud-on-k8s/index.html) I tried to access the documentation for the versions _Master_ (not sure if this should be visible at all) and _1.2_.

1. If I choose Elastic [Cloud on Kubernetes: 1.2](https://www.elastic.co/guide/en/cloud-on-k8s/1.2/index.html), -> 404.
2. If I choose master and go to [Deploy ECK, in your Kubernetes cluster](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-deploy-eck.html), the download link for the CRD points to [https://download.elastic.co/downloads/eck/1.2.0/all-in-one.yaml
](https://download.elastic.co/downloads/eck/1.2.0/all-in-one.yaml) This just displays **Not found**.
3. If I use the dropdown menu _Elastic Cloud on Kubernetes_ and choose _1.2_, I get an alert:
`This page is not available in the docs for version:1.2`

I guess 1 & 3 are connected.  

**What did you expect to see?**
1. Documentation.
2. Downloadable `all-in-one.yaml` file for ECK 1.2.0
3. see 1.

**What did you see instead? Under which circumstances?**
Circumstances are described above.

What did I see:
1. 404 - Douglas Adams
```
404Well, that about wraps it up for this page
`I refuse to prove that I exist,’ says Page, `for proof denies faith, and without faith I am nothing.’

`But,’ says Man, `The Babel fish is a dead giveaway, isn’t it? It could not have evolved by chance. It proves you exist, and so, therefore, by your own arguments, you don’t. QED.’

`Oh dear,’ says Page, `I hadn’t thought of that,’ and promptly disappears in a puff of logic.
```
2. **Not Found**
3. **This page is not available in the docs for version:1.2**

**Comment by anyasabo** [comment]
>If I choose Elastic Cloud on Kubernetes: 1.2, -> 404.

This does not seem to be the case currently, https://www.elastic.co/guide/en/cloud-on-k8s/1.2/index.html returns a 200. I wonder if this was just while it was building earlier today as these were recently added.

>If I choose master and go to Deploy ECK, in your Kubernetes cluster, the download link for the CRD points to https://download.elastic.co/downloads/eck/1.2.0/all-in-one.yaml
This just displays Not found.

1.2.0 is not released yet so this makes sense. This page (and all pages on the master and 1.2 branches currently): https://www.elastic.co/guide/en/cloud-on-k8s/master/index.html
warns this is pre-release documentation at the top in a highlighted box:

>You are looking at preliminary documentation for a future release. Not what you want? See the current release documentation. 

>If I use the dropdown menu Elastic Cloud on Kubernetes and choose 1.2, I get an alert:
This page is not available in the docs for version:1.2

This is not uncommon, not all pages exist in all branches. It's not clear which page you were trying this on though.

Closing this out as all of this appears to be the expected behavior, please re-open if I misunderstood.
