### ISSUE TITLE
Flaky integration test TestDelayingQueueInvariants

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3557]
https://devops-ci.elastic.co/job/cloud-on-k8s-pr/4225/testReport/junit/github/com_elastic_cloud-on-k8s_pkg_controller_license/Run_tests_in_parallel___Run_unit_and_integration_tests___TestDelayingQueueInvariants_no_dedup_ing_when_delaying/

```
=== RUN   TestDelayingQueueInvariants/no_dedup'ing_when_delaying
    license_controller_integration_test.go:226: 
        	Error Trace:	license_controller_integration_test.go:226
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestDelayingQueueInvariants/no_dedup'ing_when_delaying
    --- FAIL: TestDelayingQueueInvariants/no_dedup'ing_when_delaying (0.02s)
```

**Comment by barkbay** [comment]
I think there is a possible race condition here:

```golang
			adds: func(q workqueue.DelayingInterface) {
				q.Add(item)
				q.AddAfter(item, 1*time.Millisecond)
			},
			expectedObservations: 2,
```

 If the test execution is too slow the delayed item can be moved to the processing queue while the first item is still being processed. In that case the item might be discarded because either:

The non-delayed item is still scheduled to be processed and already in the `dirty` set:

```golang
// Add marks item as needing processing.
func (q *Type) Add(item interface{}) {
	[...]
	if q.dirty.has(item) {
		return
	}
```

Or the non-delayed item is being processed (i.e. between a `Get()` and a `Done(item)`):

```golang
// Add marks item as needing processing.
func (q *Type) Add(item interface{}) {
	[...]

	if q.processing.has(item) {
		return
	}
```

A solution would be to use a virtual clock as it is done in the upstream tests: https://github.com/kubernetes/client-go/blob/dea2c884774c3206743910693d4cc230d44321d4/util/workqueue/delaying_queue_test.go#L30-L32 Unfortunately since we don't have access to some of the private fields it is tricky to apply the same logic in our tests.

The only solution I have mind so far is to increase the delay to mitigate this race condition.

**Comment by barkbay** [comment]
Long time no see ... it failed today:

```
=== Failed
--
  | === FAIL: pkg/controller/license TestDelayingQueueInvariants/but_dedup's_and_updates_item_within_the_wait_queue (0.03s)
  | license_controller_integration_test.go:228:
  | Error Trace:	/..../elastic/cloud-on-k8s-operator/pkg/controller/license/license_controller_integration_test.go:228
  | Error:      	Not equal:
  | expected: 1
  | actual  : 0
  | Test:       	TestDelayingQueueInvariants/but_dedup's_and_updates_item_within_the_wait_queue
  | --- FAIL: TestDelayingQueueInvariants/but_dedup's_and_updates_item_within_the_wait_queue (0.03s)
  |  
  | === FAIL: pkg/controller/license TestDelayingQueueInvariants (2.07s)
```

Let's see if this happens regularly before we investigate again...
