### ISSUE TITLE
Enterprise Search part of TestSamples E2E test fails

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3821]
In the last three builds:
https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp/252/#showFailuresLink
https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp/253/#showFailuresLink
https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp/254/#showFailuresLink

**Comment by barkbay** [comment]
I didn't investigate this one but given [this known issue ](https://github.com/elastic/cloud-on-k8s/issues/3656) I guess it's failing because the stack version has been upgraded to `7.9.2`:

https://github.com/elastic/cloud-on-k8s/blob/d2fe6c63dfa6193885366553595537e343fa74c5/test/e2e/test/enterprisesearch/builder.go#L19-L24
