### ISSUE TITLE
ci-build-image invalid credentials

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#3906]
Looks like https://github.com/elastic/cloud-on-k8s/pull/3893 is failing because `ci-build-image` is using invalid docker credentials:

https://devops-ci.elastic.co/job/cloud-on-k8s-pr/4872/console

```
11:38:45  Successfully built bbd1c698f6aa
11:38:45  Successfully tagged docker.elastic.co/eck-ci/eck-ci-tools:290d60ed
11:38:45  Push docker.elastic.co/eck-ci/eck-ci-tools:290d60ed...
11:38:45  denied: requested access to the resource is denied
11:38:45  Retry 1/5 exited 1, retrying in 1 seconds...
11:38:45  denied: requested access to the resource is denied
11:38:45  Retry 2/5 exited 1, retrying in 2 seconds...
11:38:45  denied: requested access to the resource is denied
11:38:45  Retry 3/5 exited 1, retrying in 4 seconds...
11:38:48  denied: requested access to the resource is denied
11:38:48  Retry 4/5 exited 1, retrying in 8 seconds...
11:38:56  denied: requested access to the resource is denied
11:38:56  Retry 5/5 exited 1, no more retries left.
11:38:56  The push refers to repository [docker.elastic.co/eck-ci/eck-ci-tools]
11:38:56  The push refers to repository [docker.elastic.co/eck-ci/eck-ci-tools]
11:38:56  The push refers to repository [docker.elastic.co/eck-ci/eck-ci-tools]
11:38:56  The push refers to repository [docker.elastic.co/eck-ci/eck-ci-tools]
11:38:56  The push refers to repository [docker.elastic.co/eck-ci/eck-ci-tools]
11:38:56  Makefile:63: recipe for target 'ci-build-image' failed
11:38:56  make[1]: *** [ci-build-image] Error 1
11:38:56  make[1]: Leaving directory '/var/lib/jenkins/workspace/cloud-on-k8s-pr/.ci'
11:38:56  Makefile:42: recipe for target 'ci' failed
```

This doesn't crop up in other PRs because we only push when something changes in the CI image. I didn't get a chance to look into it so wanted to create the issue just to make sure it's not forgotten.

**Comment by david-kow** [comment]
I took a look at it and it seems to me that we are not trying to log in with admin creds, ie. we just exit here:
https://github.com/elastic/cloud-on-k8s/blob/5ba17790563f24d368e463f65b166fc3aa69b525/hack/docker-push.sh#L29-L32

The only reason for that would be if there was already a docker login, but with credentials that don't allow pushing. I can't see us doing it, so maybe the CI worker is prepped with some docker config before we even start?

We don't see it elsewhere (for instance when building ECK image) because then, we build it from within the container and the `config.json` file is not present at all:

```
15:26:09  grep: /root/.docker/config.json: No such file or directory
15:26:09  Authentication to docker.elastic.co...
15:26:09  Login Succeeded
```

**Comment by pebrc** [comment]
I am closing this for now as we have removed the login caching. It seems indeed to be the case that the Jenkins workers create a default Docker config file.
