### ISSUE TITLE
Autoscaling: dynamic scaling of cpu requests

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#4021]
There will be no CPU requirement in the first version of the Elasticsearch autoscaling API. But users might expect the CPU to scale dynamically as other metrics (memory and storage) are scaling.

An approach would be to scale the CPU proportionally to the memory (which is expected to be always present in the autoscaling API response).

As an example, if user sets an allowed range of
* 2G → 8G for memory
* 1 → 4 for CPU

Then:

* If the requested amount of memory is a third of the allowed range, 4G, then the amount of CPU requested would be 2 _(which is also a third of the range [1,4])_
* If the requested amount of memory is 2/3 of the allowed range, 6G, then the amount of CPU requested would be 3 _(which is also 2/3 of the range [1,4])_
* If the maximum amount of memory is requested then the maximum amount of CPU would also be requested.

Millicores would be rounded up to the next whole CPU.

If there is no CPU in the autoscaling specification then CPU requests would not be managed by the operator, instead the value set by the user would be reused.

**Comment by david-kow** [comment]
Is this something we really need to have right now? Could we just not do anything with CPU until API supports it? It seems to me that we arbitrary choose the CPU/mem correlation. The assumption that CPU has to scale linearly with memory doesn't always hold which may lead to actually doing a disservice to the user which will have certain expectations for autoscaling. We would also need to explain and document this behavior twice (now and when API supports it).

**Comment by barkbay** [comment]
I started thinking about this feature because of my journey as a user:
* If I can only set storage and memory in the autoscaling spec it means that by defaults CPU requests are always set to 100m. 100m ensures that the Pod is in the Burstable QoS, but I believe I would expect the CPU request to also grow.
* I can set some, arbitrary, static, resources in all the `podTemplates`, but it feels odd to have part of the resources managed in the autoscaling spec _(memory and storage)_ and another part _(cpu)_ in the `podTemplate`.

> [...] which may lead to actually doing a disservice to the user

Do you have any specific use case in mind ? We would only set CPU requests by default, which is mostly used by the scheduler to ensure that a Pod has enough of resources. Also the user would be able to set the same value for the min and the max to manually enforce CPU requests in autoscaling policies without using on the algorithm.

> We would also need to explain and document this behavior twice

CPU requests will always fluctuate between a min and max. What might change in the future are CPU predictions which will be more accurate. I agree that it is a change, but I think this is something that will happen later as I'm pretty sure the algorithm will be improved at some point anyway.

**Comment by david-kow** [comment]
> * I can set some, arbitrary, static, resources in all the `podTemplates`, but it feels odd to have part of the resources managed in the autoscaling spec _(memory and storage)_ and another part _(cpu)_ in the `podTemplate`.

I think that speaks to me the most - defining resources in multiple places is not great. But having said that, I'd argue that it's better to compromise on UX rather than to pretend that we have a feature that ES itself doesn't have 🙂 If that would be a good approximation, wouldn't ES itself start with that?
 
> > [...] which may lead to actually doing a disservice to the user
> 
> Do you have any specific use case in mind ?

Any case where memory needed drops, but CPU required increases (less state, more queries?). 

> > We would also need to explain and document this behavior twice
> 
> CPU requests will always fluctuate between a min and max. What might change in the future are CPU predictions which will be more accurate. I agree that it is a change, but I think this is something that will happen later as I'm pretty sure the algorithm will be improved at some point anyway.

We will definitely need to explain right now that this is not "true" autoscaling and extrapolates memory requirements to CPU. And later we will need to state the difference in behavior again. I think there is a difference, because we won't even mention improvements on Stack side (like we don't for any other Stack features), but we will have to explain how we went from coming up with number on ECK side to ES. Same goes for, further down the road, updating to newer ES (with CPU autoscaling) on old ECK (with our CPU autoscaling).

To try to look at this from a user point of view: I'd set the CPU min to min for the given app and max to roughly my hosts have. Let's say 1-64. For memory I'd follow apps recommendations, so probably 1-64GB. It seems to me that 32/64GB per ES node is common and often recommended (so I'd expect autoscaling to be scaling that far) but matching this with 32/64 cores is likely an overkill. As a user I'd be very surprised that ES requires this much.

Ultimately, I'll be fine both ways 🙂 For me, this is just about setting the expectations right - this works, this doesn't (but it will at some point!). If something is not ready on Stack side, I'd be comfortable saying that outright. I think it would be nice if we would involve ES team to get their thoughts - it might be that my concerns (with how this might affect user clusters) will be invalidated.

**Comment by pebrc** [comment]
I think the proposal to scale CPU alongside memory makes a lot of sense to me. If I understand you correctly then we could seemlessly switch from this operator-powered linear scaling to honoring the autoscaling signal from Elasticsearch if that contains CPU resources at some point in the future.

**Comment by barkbay** [comment]
>  If I understand you correctly then we could seemlessly switch from this operator-powered linear scaling to honoring the autoscaling signal from Elasticsearch if that contains CPU resources at some point in the future.

👍 Yes, absolutely.

**Comment by barkbay** [comment]
Implemented in https://github.com/elastic/cloud-on-k8s/pull/4173
