### ISSUE TITLE
TestVersionUpgradeTwoNodes68xTo7x is flaky

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#4104]
```
=== RUN   TestVersionUpgradeTwoNodes68xTo7x/Elasticsearch_cluster_health_should_not_have_been_red_during_mutation_process
    steps_mutation.go:119: 
        	Error Trace:	steps_mutation.go:119
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 31
        	Test:       	TestVersionUpgradeTwoNodes68xTo7x/Elasticsearch_cluster_health_should_not_have_been_red_during_mutation_process
    steps_mutation.go:121: Elasticsearch cluster health check failure at 2021-01-12 03:58:07.993913084 +0000 UTC m=+8005.583522891: Get "https://test-version-up-2-68x-to-7x-l8t6-es-http.e2e-r1a7g-mercury.svc:9200/_cluster/health": context deadline exceeded
```

**Comment by charith-elastic** [comment]
Looking at the [output of the failed test](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-stack-versions/309/testReport/github/com_elastic_cloud-on-k8s_test_e2e_es/Run_tests_for_different_Elastic_Stack_versions_in_GKE___7_3_2___TestVersionUpgradeTwoNodes68xTo7x_Elasticsearch_cluster_health_should_not_have_been_red_during_mutation_process/), it appears that the cluster health request was constantly timing out. Looking at the dump, I can't see why. The service and the pods seem to have been in a healthy state. The only odd thing I noticed is the following exception in one of the Elasticsearch nodes;

```
exception caught on transport layer [Netty4TcpChannel{localAddress=0.0.0.0/0.0.0.0:9300, remoteAddress=/10.28.128.4:55378}], closing connection" , 
"stacktrace": ["io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Empty client certificate chain"
```

I ran this test multiple times and couldn't reproduce the problem. My hunch is that the above failure was due to some transient issue in GKE at that time. Let's keep an eye on the next nightly run to see if the problem happens again.

**Comment by charith-elastic** [comment]
I haven't seen this one come up again for a while. Let's close for now and reopen if it occurs again.
