### ISSUE TITLE
 eck-operator-crds chart should put CRDs in crds/

### ISSUE THREAD

**Issue by pisto** [elastic/cloud-on-k8s#4222]
Helm has a special handling of CRDs (https://helm.sh/docs/topics/charts/). CRDs should not be placed in the `templates/` directory but rather in the `crds/` directory. Currently, conflicts can happen when upgrading the chart (because Helm expects some standard labels such as `meta.helm.sh/release-name`) or when installing over an installation made without Helm. Using the `crds/` approach would also make it easier to embed this chart as a sub-chart for other deployments, because then the CRDs would appear under the `.Capabilities` values of Helm.

**Comment by charith-elastic** [comment]
This was an intentional choice to work around the fact that Helm does not update CRDs once they are installed. See https://github.com/helm/helm/issues/5871 for more details.  ECK CRDs are still evolving and we want to be able to provide a smoother upgrade experience for users without requiring them to manually update the CRDs.

I am not sure I understand how using the special CRD handling feature of Helm would prevent any of the problems you mentioned. If Helm finds existing resources in the cluster not managed by it, it would fail anyway wouldn't it?

**Comment by pisto** [comment]
You are right on both accounts, sorry for the noise.
