### ISSUE TITLE
Using Mittwald Kubernetes-Secret-Generator

### ISSUE THREAD

**Issue by timvol** [elastic/cloud-on-k8s#4492]
I want create multiple users and roles upon container creation as described on [https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-users-and-roles.html](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-users-and-roles.html). I'm using ArgoCD for the entire setup and using [https://github.com/mittwald/kubernetes-secret-generator](https://github.com/mittwald/kubernetes-secret-generator) to generate randomized but for ECK I found no way how I can use the Kubernetes-Secret-Generator.

Is anyone using the mentioned secrets generator in ECK or has an idea how I can use it?

**Comment by thbkrkr** [comment]
Hi Tim,

[mittwald/kubernetes-secret-generator ](https://github.com/mittwald/kubernetes-secret-generator) does not seem usable for this because the secrets referenced in `spec.auth.fileRealm` to define users and roles require password hashes (which you can get using the [elasticsearch-users tool](https://www.elastic.co/guide/en/elasticsearch/reference/current/users-command.html)) and not passwords directly.

**Comment by thbkrkr** [comment]
Please use Github issues only for actual bug reports and feature requests.

You can find an overview which features are included in the Basic license here https://www.elastic.co/subscriptions

For questions around ECK please use our discuss forum at https://discuss.elastic.co/c/eck.
