### ISSUE TITLE
Beats secure settings are not updated

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#4527]
The Heartbeat resource uses an `hostPath` volume to persist keystore data.

Since https://github.com/elastic/cloud-on-k8s/pull/3295, we skip the keystore creation and the secrets addition if the keystore has already been initialized. 

This makes it impossible to add or update a secure settings in the keystore.

Workaround: manually delete the file `/var/lib/default/hb/heartbeat-data/elastic-internal-init-keystore.ok` from disk on each k8s node.

Potential fix: move the keystore data inside the container and not in the data path.

**Comment by barkbay** [comment]
It took me some time to understand that my Filebeat instance, deployed with a  1 replica `Deployment`,  was either failing or running randomly depending on the host where the Pod was scheduled. I spent a lot of time debugging the init container while the culprit was the `hostPath` which, depending on the host, was containing a different version of my keystore.

Also it is painful to delete both the flag file and the keystore on the whole K8S cluster to get back to an expected state.

IMHO it would be great if we can have this one fixed or documented as a known issue somewhere, I'm pretty sure other users using a `Deployment` and some secure settings will eventually hit this one too.

I'm wondering if this can also affect `Agent`.

**Comment by ArjonBu** [comment]
I am curious, why isn't the keystore file in the container? This would make more sense because it will be more stateless and the file would be recreated for sure when the pod is killed.

**Comment by barkbay** [comment]
> I am curious, why isn't the keystore file in the container?

Because `Filebeat` creates the keystore in `path.data`, which is supposed to be persisted.

**Comment by barkbay** [comment]
I think a simple fix here would be to not create a flag. The reason is that in the context of `Beats` a keystore can be created with the option `--force`, for example: `filebeat keystore create --force` This allows to create a new keystore, even if there is an existing one. It would also have the benefit of fixing existing deployments.

I think I'll explore this option.

**Comment by david-kow** [comment]
Hey @barkbay, maybe I'm missing something, but wasn't that the behaviour before #3295 was introduced? Should we just revert that PR? At least Elasticsearch (0) and Beats (1) seem to ignore changes made to keystore when they are already running.

(0): https://www.elastic.co/guide/en/elasticsearch/reference/current/elasticsearch-keystore.html#elasticsearch-keystore-description
> Modifications to the keystore do not take effect until you restart Elasticsearch.

(1): https://github.com/elastic/beats/blob/b772f2aa452afed1b8397b44313d874c69ea62ab/libbeat/keystore/keystore.go#L43-L46
> // Keystore implement a way to securely saves and retrieves secrets to be used in the configuration
// **Currently all credentials are loaded upfront and are not lazy retrieved**, we will eventually move
// to that concept, so we can deal with tokens that has a limited duration or can be revoked by a
// remote keystore.

**Comment by barkbay** [comment]
> Should we just revert that PR?

If we revert the PR we are likely to hit https://github.com/elastic/cloud-on-k8s/issues/3294 again (or maybe I don't understand your proposal)

> At least Elasticsearch (0) and Beats (1) seem to ignore changes made to keystore when they are already running.

I think this is why we have the label `elasticsearch.k8s.elastic.co/secure-settings-hash` in the context of Elasticsearch.
I would have expected the same thing for beat, but it seems we have a bug here, see #4926

That being said I'm now wondering how the keystore is supposed to be managed if a user want to deploy several instances of Filebeat on a same node ?
