### ISSUE TITLE
Inconsistent (with documentation) heap size management

### ISSUE THREAD

**Issue by aksdb** [elastic/cloud-on-k8s#4665]
## Bug Report
**What did you do?**

Omit the heap size settings for the pod(s), as documented in the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/important-settings.html#heap-size-settings).

**What did you expect to see?**

The JVM automatically scales according to the pod limits.

**What did you see instead? Under which circumstances?**

`-Xms1024m -Xmx1024m` gets added to the startup parameters, forcing the JVM into a (likely) suboptimal memory restriction.

**Environment**

* ECK version: eck-operator 1.6.0

**Comment by barkbay** [comment]
Could you clarify:
* what version of Elasticsearch you are using ? The feature you mentioned is only available since Elasticsaerch `7.11`
* what memory limit/request are allocated to the container ?
* if you can enter the Elasticsearch container, could you provide the result of the following command: `ps -eo args | grep java`

Thanks

**Comment by mtparet** [comment]
We got hit by the same issue, there is a bug before elasticsearch 7.17.4 https://github.com/elastic/elasticsearch/issues/86431
