### ISSUE TITLE
TestMutationWhileLoadTesting fails due to failed connection attempts

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#5263]
We see quite a few test failures during this test with 
```
“Get \“https://test-while-load-testing-nfkr-es-http.e2e-r9ymu-mercury.svc.cluster.local:9200/\“: dial tcp 0.0.0.0:0-\u003e10.48.22.216:9200: connect: connection reset by peer”
```

This happens on various ES versions 6.8.x and 7.13.4 are recent examples. E.g. https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-stack-versions/640//testReport

**Comment by thbkrkr** [comment]
This occurred today with `7.6.2` and yesterday with `7.16.2` on `1.20.12-gke.1500`.

**Comment by thbkrkr** [comment]
I did archeology and it happened more than I thought.

```
02/02/2022 7.6.2
01/02/2022 7.16.2
28/01/2022 7.6.2
26/01/2022 6.8.17
25/01/2022 7.16.2
25/01/2022 7.16.2
19/01/2022 7.13.4 
17/01/2022 6.8.15 
14/01/2022 7.14.0
11/01/2022 7.14.0

22/12/2021 8.0.0-SNAPSHOT
21/12/2021 7.12.1
21/12/2021 7.13.4
13/12/2021 7.15.2
10/12/2021 7.9.3
26/11/2021 7.9.3
16/11/2021 7.15.0
08/11/2021 7.15.0
05/11/2021 7.6.2
02/11/2021 7.9.3
22/10/2021 7.6.2
14/10/2021 7.13.4
24/09/2021 7.13.4
14/09/2021 7.13.4

03/12/2020 7.9.2

13/12/2019 first appearance in pr #2233
```

We got one first appearance in [#2233](https://github.com/elastic/cloud-on-k8s/pull/2233#pullrequestreview-330510280), one occurrence in 2020 and then it seems to have really started in September 2021. So odd.

The only thing I feel that might be more or less related to this is the merge of #4801 on 01/09/2021 because of the date close to 14/09/2021 and the link with #2233. Although it's probably a coincidence.

**Comment by thbkrkr** [comment]
Superseeded by #5659.
