### ISSUE TITLE
Call desired nodes API upon desired state changes

### ISSUE THREAD

**Issue by henningandersen** [elastic/cloud-on-k8s#5528]
## Proposal

We would like to have ECK call the Elasticsearch [desired nodes API](https://www.elastic.co/guide/en/elasticsearch/reference/8.1/update-desired-nodes.html) whenever a new desired state is available, before carrying out steps towards that new desired state.

This will enable Elasticsearch to make better decisions (like avoiding unnecessary and expensive shard movements), improving the user experience, safety, avoiding data loss and speeding up reaching the desired state.

**Comment by henningandersen** [comment]
Thanks @barkbay for taking this on. I will try to respond to your questions below:

> My hunch is that we should continue whatever the error is

I'd say not to continue if it fails any validation etc. Invoking the desired nodes API is done at URGENT priority and bypasses circuit breakers in order to ensure it succeeds. If it cannot store its state, it is likely that a node will not be able to join either.

I think we could live with trying hard (with some retries) and then continuing if it fails. I'd hope it would be reconciled eventually then though? Also, it may leave the cluster in a less than ideal state (but likely not worse than today until we rely on this information more heavily).

> Would it however prevent new nodes from joining the cluster for example?

No, we consider that a health issue, not something we validate against.

>  would be tempted to use something that uniquely identifies the Elasticsearch resource, like the UID ... Upon a restore, even if the Elasticsearch resource is recreated with a same name, it would allow to start a new history

IIUC, this sounds exactly right. We should only switch history ID in extreme cases like restoring k8s data store (i.e., going backwards in version numbers).

> I was thinking about using the generation field, (generation is a metadata field incremented when the spec of a resource is changed). It should be fine as long as discontinuous versions are allowed?

Yes, I think generation is the right field to use here. There can be holes in the sequence, no problem. As long as it is always increasing when new changes happen.

> The resources allocated to a Pod may not be known to the operator

I believe we validate that cpu and memory is specified (@fcofdez keep me honest here). I think not having these could be problematic, at least to autoscaling and balancing. Is this a normal configuration or an atypical one?

> The actual storage capacity might be greater than the one requested ... Is it a problem if the capacity observed by Elasticsearch is greater than the one set in the desired API?

Yes, that could turn out problematic. For instance autoscaling might say that we need one more additional node until a new node from a previous autoscaling event actually joins.

**Comment by fcofdez** [comment]
> I believe we validate that cpu and memory is specified (@fcofdez keep me honest here). I think not having these could be problematic, at least to autoscaling and balancing. Is this a normal configuration or an atypical one?

Yes, `processors`, `memory` and `storage` are required fields for the desired nodes.

**Comment by barkbay** [comment]
> I'd say not to continue if it fails any validation etc. Invoking the desired nodes API is done at URGENT priority and bypasses circuit breakers in order to ensure it succeeds. If it cannot store its state, it is likely that a node will not be able to join either.

I made a simplified diagram of the reconcile loop part where nodes are updated _(blue boxes are some comments relevant to our current discussion)_:

![image](https://user-images.githubusercontent.com/976373/165082470-5ed3a35c-9e91-47ff-b4c5-5b23d29de0da.png)

As mentioned in the diagram we may want to upgrade nodes even if the API is not available, a common use case is when all the nodes are in a crashloop state, for example when nodes are OOMing because of a memory limit which is too low. Note that it may take some time _(seconds, maybe a few minutes...)_ for the operator to be able to sync with the desired node API. Do you think it is acceptable from the Elasticsearch point of view?

If yes I think we may want to call the desired node API somewhere between `BuildExpectedResources` and `HandleUpscaleAndSpecChanges`, with the following error handling if the API is not available:
* Update the `StatefulSet` specification in `HandleUpscaleAndSpecChanges` without upscaling the number of replicas as you suggested.
* Always call `MaybeForceUpgrade` to give a chance to the user to put a cluster back on track

**Comment by barkbay** [comment]
>> I believe we validate that cpu and memory is specified (@fcofdez keep me honest here). I think not having these could be problematic, at least to autoscaling and balancing. Is this a normal configuration or an atypical one?

> Yes, processors, memory and storage are required fields for the desired nodes.

Running a `Pod` without any explicit memory or CPU requirement is allowed in K8S. Even if setting `limits` and `requests` is [considered a best practice](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-resource-requests-and-limits) I'm not sure we want to enforce it.

Could we however consider a "degraded" mode?

1. Either at the operator level: when the allocated resources cannot be predicted by the operator, the desired nodes API would not be called.
2. Or at the Elasticsearch level: it would be ok to call the desired nodes API without providing all the resources.

Obviously in both cases the scheduling mechanism would not be considered "optimal", some advanced features would not even be available.

Regarding the storage capacity we may have the actual capacity in the `PersistentVolumeClaim` status or in the `PersistentVolume` itself, I have to dig a little bit more this option though..

**Comment by barkbay** [comment]
I spent some time today thinking about what should be the value for the `processors` field. There are 4 possible situations in Kubernetes:

1. Neither `limits.cpu` nor `requests.cpu` is set
  ⮕ It is impossible to guess or act upon the available processor value. This would fall under the "degraded" mode.
2. Only `limits.cpu` is explicitly set. In that case Kubernetes sets `requests.cpu` to the same value as `limits.cpu`
  ⮕ We can use that value for the `processors` field
3. Only `requests.cpu` is explicitly set
  ⮕ From an ECK perspective we can only provide the CPU request, but depending on how the desired nodes API is used I'm not sure it always makes sense ?
4. Both `limits.cpu` and `requests.cpu` are explicitly set
  ⮕ Same as `3.`, I think that selecting the right value depends on how the the `processors` field is used internally by Elasticsearch.
  
  I'm wondering if an alternative would not be to provide the 2 values to Elasticsearch. Would it possible that simplifying to a single value might be a bit too simplistic, and might eventually prevent Elasticsearch to take some accurate decisions?
  
  ```json
  {
    "nodes" : [
        {
            "settings" : {},
            "processors" : { "request" : 8, "limit" : 4 },
            "memory" : "58gb",
            "storage" : "1700gb",
            "node_version" : "{version}"
        }
    ]
}
  ```

**Comment by fcofdez** [comment]
I think that when `limits.cpu` is known we should rely on that value as it's the CPU upper bound that Elasticsearch would get.
When only `requests.cpu` is set I guess that we could consider that Elasticsearch would get at _most_ that number of CPUs, we cannot make other assumptions in that case I think?. 

About the changes to the API, I feel like these concepts are too k8s specific, but since k8s is becoming the facto orchestrator I guess it should be fine to use the same names, wdyt @henningandersen?

 One downside is that if these concepts change over time we should adapt this API and deal with both modes, 
while if we get just the number of processors for the Elasticsearch node the API can remain unchanged.

**Comment by henningandersen** [comment]
I agree that we should have both values. I'd prefer to use k8s-neutral naming rather than requests/limits. Perhaps juts min/max, i.e.:

```json
  {
    "nodes" : [
        {
            "settings" : {},
            "processors" : { "min" : 4, "max" : 8 },
            "memory" : "58gb"
            "storage" : "1700gb",
            "node_version" : "{version}"
        }
    ]
}
  ```

alternatively slightly more opinionated naming like "guaranteed" and "boosted"?

I think `request` and `limit` is swapped in the example? I.e., [`limit >= request`](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-resource-requests-and-limits).

**Comment by barkbay** [comment]
> About the changes to the API, I feel like these concepts are too k8s specific,

The orchestration layer does not manage the CPU resource directly. On Linux this is delegated to the CPU cgroups controller, which lives in the Linux kernel and is not k8s specific. You can do the same outside of K8S using [systemd](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/resource_management_guide/sec-modifying_control_groups) or [Docker](https://docs.docker.com/config/containers/resource_constraints/#cpu). That being said I agree that we shouldn't use something tied to a specific technology, I think @henningandersen 's proposal makes sense, 👍  for `min` and `max`

For information purposes here is the naming/schema used by the [Open Container Configuration](https://github.com/opencontainers/runtime-spec/#open-container-initiative-runtime-specification) API for Linux and Windows:

* For [Linux](https://github.com/opencontainers/runtime-spec/blob/031e38d55620fea0f6c668ac1465a15029fbb6ff/specs-go/config.go#L318-L335):

```golang
// LinuxCPU for Linux cgroup 'cpu' resource management
type LinuxCPU struct {
	// CPU shares (relative weight (ratio) vs. other cgroups with cpu shares).
	Shares *uint64 `json:"shares,omitempty"`
	// CPU hardcap limit (in usecs). Allowed cpu time in a given period.
	Quota *int64 `json:"quota,omitempty"`
	// CPU period to be used for hardcapping (in usecs).
	Period *uint64 `json:"period,omitempty"`
	// How much time realtime scheduling may use (in usecs).
	RealtimeRuntime *int64 `json:"realtimeRuntime,omitempty"`
	// CPU period to be used for realtime scheduling (in usecs).
	RealtimePeriod *uint64 `json:"realtimePeriod,omitempty"`
	// CPUs to use within the cpuset. Default is to use any CPU available.
	Cpus string `json:"cpus,omitempty"`
	// List of memory nodes in the cpuset. Default is to use any available memory node.
	Mems string `json:"mems,omitempty"`
	// cgroups are configured with minimum weight, 0: default behavior, 1: SCHED_IDLE.
	Idle *int64 `json:"idle,omitempty"`
}
```
 
* For [Windows](https://github.com/opencontainers/runtime-spec/blob/031e38d55620fea0f6c668ac1465a15029fbb6ff/specs-go/config.go#L527-L545):

```golang
// WindowsCPUResources contains CPU resource management settings.
type WindowsCPUResources struct {
	// Count is the number of CPUs available to the container. It represents the
	// fraction of the configured processor `count` in a container in relation
	// to the processors available in the host. The fraction ultimately
	// determines the portion of processor cycles that the threads in a
	// container can use during each scheduling interval, as the number of
	// cycles per 10,000 cycles.
	Count *uint64 `json:"count,omitempty"`
	// Shares limits the share of processor time given to the container relative
	// to other workloads on the processor. The processor `shares` (`weight` at
	// the platform level) is a value between 0 and 10000.
	Shares *uint16 `json:"shares,omitempty"`
	// Maximum determines the portion of processor cycles that the threads in a
	// container can use during each scheduling interval, as the number of
	// cycles per 10,000 cycles. Set processor `maximum` to a percentage times
	// 100.
	Maximum *uint16 `json:"maximum,omitempty"`
}
```

I did not discuss memory since my feeling is that we should require it to have the same value for both the request and the limit.

> I think request and limit is swapped in the example? I.e., [limit >= request](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-resource-requests-and-limits).

Yes

**Comment by fcofdez** [comment]
I'll modify the API to include a `min` and `max` values for the processor fields as agreed here.

**Comment by fcofdez** [comment]
I opened https://github.com/elastic/elasticsearch/pull/86434 to add the CPU ranges to the Desired Nodes API as we discussed.

**Comment by barkbay** [comment]
Regarding the settings, some of them are set using environment variables, for example:

```yaml
network:
  publish_host: ${POD_IP}
node:
  attr:
    k8s_node_name: ${NODE_NAME}
```

These environment variables are only known once the Pod is scheduled/running. Could it be a problem if not all the variables are resolved/evaluated in the `settings` field when calling the desired nodes API ?

**Comment by fcofdez** [comment]
> These environment variables are only known once the Pod is scheduled/running. Could it be a problem if not all the variables are resolved/evaluated in the settings field when calling the desired nodes API ?

The only problem is that we don't validate them upfront and some invalid settings can prevent the node from starting. do we have a list of the settings that are set using environment variables?

**Comment by barkbay** [comment]
> The resources allocated to a Pod may not be known to the operator. For example, it might be the case if the user does not provide any resource request or limits in the specification, or if default resources are set using [LimitRanges](https://kubernetes.io/docs/concepts/policy/limit-range/).

I realised that there should be no admission-time mechanism that changes or set the Pod's request or limit. Otherwise the content of the desired nodes API may diverge from what is actually allocated. Limit ranges is one of these mechanisms, but there might be others. This should be stated in the documentation.

**Comment by barkbay** [comment]
Closed by https://github.com/elastic/cloud-on-k8s/pull/5650
