### ISSUE TITLE
Elasticsearch status subresource is updated infinitely

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#5532]
Starting with #5496 the slices of nodes in the status (`DownscaleOperation.Nodes`, `UpgradeOperation.Nodes` and `UpscaleOperation.Node`) are retrieved as `nil` when empty, while the reconcile logic always ensures that this is not the case in the expected status:

```golang
// RecordNewNodes records pending node creations.
func (u *UpscaleReporter) RecordNewNodes(nodes []string) {
	if u == nil {
		return
	}
	if u.nodes == nil {
		u.nodes = make(map[string]esv1.NewNode, len(nodes)) // Here
	}
 ```

This leads `reflect.DeepEqual(previous, current)` to always return `false`: https://github.com/elastic/cloud-on-k8s/blob/371c3248c7fecab952cf04b614229eae0da80134/pkg/controller/elasticsearch/reconcile/state.go#L179-L181
The status is therefore updated infinitely.

**Comment by thbkrkr** [comment]
Just to capture a bit more context.

Before #5496, the `nodes` slices fields in the Elasticsearch status struct were required. It causes an issue with self-monitoring during the startup where the association controller wants to update the ES status of the associated ES resource before the ES controller did it. The zero-value of a slice is `nil`, so an empty `ElasticsearchStatus{}` gets nil `nodes` and sending an update of ES with this is then rejected.

One option could have been be to fix the initialization of the ElasticsearchStatus in the association controller. I involves a bit of reflection to detect that the associated resource is of type ES and to update the empty ElasticsearchStatus. With #5496, I prefered to make the `nodes` field optional but I didn't see the implications which lead us to this issue of infinite update. 

What's going on? As you said, being optional, the nodes field is always `nil` when the ES resource is returned by the API server. 
But, when the new `ElasticsearchStatus` is merged with the current `ElasticsearchStatus` before they are compared, the `nodes` fields are mutated from `nil` to empty slices. As soon as the `u.nodes` map is empty (and not nil), we allocate an empty `nodes` slice and set it L124.

https://github.com/elastic/cloud-on-k8s/blob/371c3248c7fecab952cf04b614229eae0da80134/pkg/controller/elasticsearch/reconcile/status.go#L111-L124

Then, we compare nil (`nodes` in the previous status) with empty slices (`nodes` in the current status, resulting from the merge of the new status with the previous one). Because the status seems always different, it is infinitely updated.

#5534 avoids the mutation of the `nodes` fields during the merge operation.
