### ISSUE TITLE
Aquasec Scan findings on ECK Operator Image 2.1.0

### ISSUE THREAD

**Issue by KARTHIKKUMARMURUGESAN** [elastic/cloud-on-k8s#5634]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**
While running Aquasec scan on ECK operator image 2.1.0, we are getting some vulnerabilities findings & it is not allowing us to deploy in Kubernetes as per security policy

**What did you expect to see?**

Want to get pass from Aquasec scan findings. So do we have any fix or will it get fix on ECK Operator 2.2.0 image?

**What did you see instead? Under which circumstances?**

while doing ECK 2.1.0 Aquasec scanning, i am getting block from these (CVE-2022-26280, RHSA-2022:0899 & CVE-2018-25032) vulnerabilities 

**Environment**

* ECK version:

	2.1.0

* Kubernetes information:

	* Cloud: AKS ?

	
	for each of them please give us the version you are using
```
$ kubectl version
```
1.23

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
vulnerabilities ID's : CVE-2022-26280, RHSA-2022:0899 & CVE-2018-25032
```

**Comment by pebrc** [comment]
This happens over time even if our image does not have any vulnerabilities at release time because the UBI base image we are using has quite a few applications and libraries. 

You have three options:
1. you can update the dependencies in the ECK operator image by running `microdnf update --setopt=tsflags=nodocs && microdnf clean all` and committing the result into a new image. 
2. you can wait for the next release 2.2 which is right around the corner and will come with an updated image 
3. you can wait for the release after that in which we will move (back) to a [distroless](https://github.com/GoogleContainerTools/distroless) base image which causes much less noise with vulnerability scanners.
