### ISSUE TITLE
Make timeouts configurable

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#684]
In the operator code we manipulate quite a few timeouts that could be configurable by the user:
- ES cluster timeout
- ~process manager timeout~
- ~process restart timeout~
- k8s apiserver timeout
- csr init container timeout

In most cases it makes sense to configure them at the operator level. Should some of them be configurable at the ES cluster spec level?

**Comment by pebrc** [comment]
Elasticsearch client timeouts (should be per cluster configurable)

https://github.com/elastic/cloud-on-k8s/blob/efb91c88d1bdf1647130a60e52749e9d1c62f536/pkg/controller/elasticsearch/client/client.go#L24-L26


Observer timeouts (probably also per cluster)
https://github.com/elastic/cloud-on-k8s/blob/e888a3798b1e858f0130e3e4af21b5b525808257/pkg/controller/elasticsearch/observer/observer.go#L20-L23


K8s client (should be ECK level timeouts)
https://github.com/elastic/cloud-on-k8s/blob/8f7265b227a7e854edcb6dec46c47569a26350bf/pkg/utils/k8s/client.go#L16

Licensing related timeouts/intervals (should be ECK level timouts):
https://github.com/elastic/cloud-on-k8s/blob/6ad34cbadb072fc5ee9cbe05fc49f93959bf18e1/pkg/controller/license/license_controller.go#L38-L39

Various testing related timeouts (probably OK to just change the code if needed)
https://github.com/elastic/cloud-on-k8s/blob/f4b74085134742fbe6104118238aed0c532ff77c/test/e2e/cmd/run/run.go#L34-L35

**Comment by sebgl** [comment]
A configurable k8s client timeout would have been useful for https://github.com/elastic/cloud-on-k8s/issues/3441.

**Comment by charith-elastic** [comment]
Is there a compelling reason to make the Elasticsearch client timeout configurable per-cluster? From a user perspective this timeout has no effect on the behaviour of the Elasticsearch cluster they are provisioning, so it feels out-of-place in the CR.

If we add the field to the public API (CRD), some users could feel compelled to set it without understanding the implications properly. A short timeout could destabilise the operator because it will be unable to communicate with Elasticsearch to do anything. Conversely, a long timeout could make the reconciliation loops too slow.

I think that it's sufficient to have a single, operator-level timeout for the Elasticsearch client. Since the operator is stateless, restarting it to increase that value is not an onerous task either.

**Comment by anyasabo** [comment]
I think it's reasonable to start with an operator level timeout configuration. It seems premature to set it per CR. I can see how it would be useful to set it per CR in a situation like elastic cloud, where you might just want to unblock a particular overloaded cluster to get it back to a better state. Overriding all timeouts and redeploying the operator seems like a heavy handed way of doing that in comparison. But it seems like we can leave that as a future optimization to approach if necessary.

**Comment by sebgl** [comment]
++ to what Anya said. If the operator manages 100s of clusters, I can very well see cases where we may want to manually increase the timeouts to eg. 10 mins in some cases (overloaded cluster with large cluster state for example), without impacting the default timeout for other stable clusters.

**Comment by charith-elastic** [comment]
Having thought about it more, I think annotations are a better way to express these kinds of temporary config changes affecting the operator. A field in the CR is odd because it is not strictly required to describe an Elasticsearch cluster. It is also a strong commitment to make because we need to keep supporting that field until the CRD version is deprecated.
