### ISSUE TITLE
Helm Chart.lock no longer present

### ISSUE THREAD

**Issue by MShekow** [elastic/cloud-on-k8s#6894]
## Proposal: add `Chart.lock` to _published_ Helm charts

From what I understand, https://github.com/elastic/cloud-on-k8s/pull/6734 removed the `Chart.lock` file from Git. I think that an unintended side-effect of this is that the lock file is now missing entirely (since 2.8.0), even in the published tar.gz chart archives.

However, having a lock file is good practice for reproducibility reasons, and should therefore be at least present in the _published_ charts.

**Comment by thbkrkr** [comment]
#6734 does not remove the `Chart.lock` from Git but indeed it stops generating them during the release and therefore they are no longer in the published `.tar.gz` chart archives. They are no longer generated because we stop doing `helm update dependency`. I will see how to restore them.

I noticed that only the parent charts get a `Chart.lock`, not the childrens while we also release them independently of their parents.

**Comment by thbkrkr** [comment]
To generate the `Chart.lock`, I didn't find another way that doing `helm dependency update`, which can be done as code or exec'ing helm.

```go
// option 1
man := &downloader.Manager{Out: ioutil.Discard, ChartPath: tempChartDirPath}
if err := man.Update(); err != nil {
	return err
}
// option 2
cmd := exec.Command("helm", "dependency", "update", ".")
cmd.Dir = tempChartDirPath
if err := cmd.Run(); err != nil {
	return err
}
```

I opted for option 1.
