### ISSUE TITLE
ECK Stack Helm Charts - Enterprise licensed feature note being removed in version 2.12

### ISSUE THREAD

**Issue by simonecaf** [elastic/cloud-on-k8s#7676]
Good morning,
I noticed a licensing related note difference between previous versions and version 2.12.

In version 2.11 I can see [a note in here](https://github.com/elastic/cloud-on-k8s/blob/2.11/docs/orchestrating-elastic-stack-applications/stack-helm-chart.asciidoc) defining what follows:

> Note | ECK Stack Helm Charts are currently being released as an Enterprise licensed feature.

In version 2.12 the note disappeared, so I cannot understand if this is intentional or not.

It would be good to further clarify the licensing aspects of Elasticsearch ECK vs ECK Stack Heml Charts **with a clear distinction** as after [this issue in here](https://github.com/elastic/helm-charts/issues/1731) there's a lot of confusion about which chart people can use for free.

**Comment by Kushmaro** [comment]
Hi @simonecaf , thank you for the query.
We've recently decided that since ECK is the best way to run the Elastic Stack, and Helm charts are also the best way to deploy containers, that we would remove the Enterprise license check from those, and enable it for basic users. 

We will continue to develop ECK's Enterprise capabilities, such as autoscaling, stackconfig policies, (and more things to come) to drive further value for our licensed customers

**Comment by simonecaf** [comment]
Hello @Kushmaro,
thanks for the quick reply.

Frankly speaking I fully agree with the decision and I hope the news will make disappointed developers happy again 😀.
