### ISSUE TITLE
Kubernetes 1.31 Support

### ISSUE THREAD

**Issue by kaykhan** [elastic/cloud-on-k8s#8096]
Hi we are building a new cluster in 1.31 and would like to continue using ECK. 

The official documentation sugguest 1.31 is not supported for the latest ECK 2.14.

https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s_supported_versions.html

Is there an ETA for 1.31 support? thank you

**Comment by rhr323** [comment]
Hey,

Thank you for your interest in ECK!

ECK 2.14 was released prior to the release of Kubernetes 1.31, which is why Kubernetes 1.31 is not currently listed as a supported version. However, we are planning a new ECK release sometime in November, and that release will likely include support for Kubernetes 1.31.

We appreciate your patience and interest in ECK, and if you have any further questions, feel free to reach out.
