### ISSUE TITLE
(Doc) How-to access operator generated Kibana encryptionKey

### ISSUE THREAD

**Issue by stefnestor** [elastic/cloud-on-k8s#8129]
👋 howdy, team!

[Scale out a Kibana deployment](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-kibana-advanced-configuration.html#k8s-kibana-scaling) covers the three `encryptionKey` settings required to scale out Kibana and/or successfully migrate SavedObjects/Reports across clusters: ( `xpack.security.encryptionKey`, `xpack.reporting.encryptionKey`, `xpack.encryptedSavedObjects.encryptionKey`). 

It reports that these keys are "automatically generated by the operator" and an internal reference claims these persist across operator/stack version upgrades. However, for a customer to migrate data across clusters they need to access these values and I haven't been able to figure out how to output them. I had expected them to report under `kubectl get secrets` and/or the ECK Diagnostic's `secrets.json`. 

I'm happy to update doc with provided answer or if y'all will kindly supplement how to output those operator autogenerated key-values 🙏

TIA! Stef

**Comment by kilfoyle** [comment]
Hi @elastic/cloud-k8s-operator, would any of you be able to help with this? It's a docs issue but we'd need help with Stef's question above. Thanks!

**Comment by pebrc** [comment]
>  I had expected them to report under `kubectl get secrets` and/or the ECK Diagnostic's `secrets.json`.

We do not include sensitive information in the diagnostic archive because we expect customers to share these files with us. That means no secret contents is included, only metadata. 

However you are also saying that you "expected them to report under `kubectl get secrets`" and that is indeed where you find the keys. The operator generates the keys and stores them in the Kubernetes secrets that hold the Kibana configuration file `kibana.yml`  

The file is named after the corresponding Kibana. So for a Kibana called `my-kibana` it would be: 

```
kubectl get secret my-kibana-kb-config -o json | jq -r '.data["kibana.yml"] | @base64d' | yq .xpack.security.encryptionKey
```
