### ISSUE TITLE
[Question] what is the latest compatible version for Elastic Stack 6.8.23

### ISSUE THREAD

**Issue by bindiego** [elastic/cloud-on-k8s#8312]
I am testing on Google Cloud with GKE. All the latest versions works very well as intended.

But cannot find a working combination for 6.8.23. According to the [support matrix](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s_supported_versions.html) it should be supported.

Would you please advise on that?

BTW, we can quickly reproduce on Google Cloud by using this [repo](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s_supported_versions.html)

./bin/demo.sh will launch all the latest that works,

but `./bin/demo.sh 6.8` tend to launch 6.8.23 doesn't with clear errors or clues. Thanks.

**Comment by thbkrkr** [comment]
I guess you meant this repo: https://github.com/elasticsearch-cn/elastic-on-gke.

Did you check the operator log? When I deploy https://github.com/elasticsearch-cn/elastic-on-gke/blob/develop/templates/es.demo.6.8.yml, I see this error:

`
Service "dingo-demo-6.8-es-transport" is invalid: metadata.name: Invalid value: "dingo-demo-6.8-es-transport": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
`

The operator reuses the name of the Elasticsearch resource to create the Service and dots are forbidden due to https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#rfc-1035-label-names.

Try `with dingo-demo-6-8` in [es.demo.6.8.yml](https://github.com/elasticsearch-cn/elastic-on-gke/blob/3a6b7f8dc8841d5707102df0a27f65f6ca1221f2/templates/es.demo.6.8.yml#L4) and `dingo-demo-kbn-6.8` in [kbn.demo.6.8.yml](https://github.com/elasticsearch-cn/elastic-on-gke/blob/3a6b7f8dc8841d5707102df0a27f65f6ca1221f2/templates/kbn.demo.6.8.yml#L4C11-L4C29).

**Comment by bindiego** [comment]
Thanks for your input, problem solved and now confirmed the latest 6.8.23 works with the latest ECK 2.15
