### ISSUE TITLE
Allow users to configure xpack.security.transport.ssl.certificate_authorities

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#962]
This will enable low-level support for CCR/CCS as it allows users to define a trust relationship between local cluster and all remote clusters by adding the CA certificate from the local cluster as a trusted CA in each remote cluster

**Comment by thbkrkr** [comment]
IIUC it's just about removing `XPackSecurityTransportSslCertificateAuthorities` from the blacklist of fields?

I did a quick test and I have two questions.

1/ Stop me if I'm wrong, but we want to let the user be able to override the default settings set by the operator?
In that case, I think the order of the configs to merge needs to be reversed.
https://github.com/elastic/cloud-on-k8s/blob/6901c76f95c4304e6b4e633713718ccd8635267c/operators/pkg/controller/elasticsearch/settings/merged_config.go#L27-L29


2/ I'm not sure to understand why the fields provided by the user are refused if they begins with a blacklisted field instead of using a strict comparison.
https://github.com/elastic/cloud-on-k8s/blob/52695895e4b60a9e664093c782af53a71982415d/operators/pkg/controller/elasticsearch/validation/validations.go#L78
If we remove `xpack.security.transport.ssl.certificate_authorities` from the blacklist then, the field will still be blacklisted because it's prefixed by `xpack.security.http.ssl.certificate` which is in the blacklist.

**Comment by pebrc** [comment]
I think you are right about both points.

I believe the prefix validation was added so that we can blacklist whole sub trees of configuration because we initially said `xpack.security.transport` would be the domain of the operator and we would not allow users to override those settings. This changes of course with this issue.
